const DIALOGUES = [
  {
    id: "hotel",
    title: "Im Hotel einchecken",
    emoji: "🏨",
    sub: "Otele Giriş",
    lines: [
      { speaker: "A", role: "Tourist",        de: "Guten Tag, ich habe eine Reservierung.", tr: "İyi günler, rezervasyonum var.",          pron: "İyi gjün-ler, re-ser-was-jo-num war" },
      { speaker: "B", role: "Rezeptionist",   de: "Ihr Name, bitte?",                       tr: "İsminiz, lütfen?",                         pron: "İs-mi-nis, ljüt-fen" },
      { speaker: "A", role: "Tourist",        de: "Schmidt.",                                tr: "Schmidt.",                                  pron: "Schmidt" },
      { speaker: "B", role: "Rezeptionist",   de: "Ja, fünf Nächte, Doppelzimmer.",         tr: "Evet, beş gecelik çift kişilik oda.",       pron: "E-wet, besch ge-dsche-lik tschift ki-schi-lik o-da" },
      { speaker: "A", role: "Tourist",        de: "Ist das Frühstück inklusive?",            tr: "Kahvaltı dahil mi?",                        pron: "Kah-wal-tı da-hil mi" },
      { speaker: "B", role: "Rezeptionist",   de: "Ja, Frühstück von 7 bis 10 Uhr.",        tr: "Evet, kahvaltı 7'den 10'a kadar.",          pron: "E-wet, kah-wal-tı je-di-den o-na ka-dar" },
      { speaker: "A", role: "Tourist",        de: "Danke. Wo ist der Aufzug?",               tr: "Teşekkürler. Asansör nerede?",              pron: "Te-schek-kjür-ler. A-san-sjör ne-re-de" },
      { speaker: "B", role: "Rezeptionist",   de: "Rechts, neben dem Restaurant.",           tr: "Sağda, restoranın yanında.",                pron: "Saa-da, res-to-ra-nın ja-nın-da" },
      { speaker: "A", role: "Tourist",        de: "Vielen Dank.",                            tr: "Çok teşekkürler.",                          pron: "Tschok te-schek-kjür-ler" },
      { speaker: "B", role: "Rezeptionist",   de: "Einen schönen Aufenthalt!",               tr: "İyi konaklamalar!",                         pron: "İyi ko-nak-la-ma-lar" },
    ],
  },
  {
    id: "restaurant",
    title: "Im Restaurant bestellen",
    emoji: "🍽️",
    sub: "Restoranda",
    lines: [
      { speaker: "A", role: "Tourist",  de: "Guten Abend. Einen Tisch für zwei?",        tr: "İyi akşamlar. İki kişilik masa var mı?",  pron: "İyi ak-scham-lar. İki ki-schi-lik ma-sa war mı" },
      { speaker: "B", role: "Kellner",  de: "Ja, hier bitte.",                            tr: "Evet, buyurun.",                           pron: "E-wet, bu-ju-run" },
      { speaker: "A", role: "Tourist",  de: "Danke. Die Speisekarte, bitte.",             tr: "Teşekkürler. Menü, lütfen.",               pron: "Te-schek-kjür-ler. Me-njü, ljüt-fen" },
      { speaker: "B", role: "Kellner",  de: "Bitte. Was möchten Sie trinken?",            tr: "Buyurun. Ne içmek istersiniz?",            pron: "Bu-ju-run. Ne itsch-mek is-ter-si-nis" },
      { speaker: "A", role: "Tourist",  de: "Ein Wasser und einen Tee, bitte.",           tr: "Bir su ve bir çay, lütfen.",               pron: "Bir su we bir tschaj, ljüt-fen" },
      { speaker: "B", role: "Kellner",  de: "Haben Sie schon gewählt?",                   tr: "Seçtiniz mi?",                             pron: "Setsch-ti-nis mi" },
      { speaker: "A", role: "Tourist",  de: "Ja. Ich nehme den Fisch.",                   tr: "Evet. Balık alıyorum.",                    pron: "E-wet. Ba-lık a-lı-jo-rum" },
      { speaker: "B", role: "Kellner",  de: "Sehr gerne. Guten Appetit!",                 tr: "Tabii ki. Afiyet olsun!",                  pron: "Ta-bi-i ki. A-fi-jet ol-sun" },
      { speaker: "A", role: "Tourist",  de: "Es war sehr lecker. Die Rechnung, bitte.",   tr: "Çok lezzetliydi. Hesap, lütfen.",          pron: "Tschok les-set-li-di. He-sap, ljüt-fen" },
      { speaker: "B", role: "Kellner",  de: "Natürlich, sofort.",                         tr: "Tabii, hemen.",                            pron: "Ta-bi-i, he-men" },
    ],
  },
  {
    id: "markt",
    title: "Auf dem Markt einkaufen",
    emoji: "🛒",
    sub: "Çarşıda",
    lines: [
      { speaker: "A", role: "Tourist",   de: "Guten Morgen! Wie viel kostet das?",          tr: "Günaydın! Bu ne kadar?",                   pron: "Gjün-aj-dın! Bu ne ka-dar" },
      { speaker: "B", role: "Verkäufer", de: "Zwei Euro das Kilo.",                          tr: "Kilo iki euro.",                            pron: "Ki-lo i-ki eu-ro" },
      { speaker: "A", role: "Tourist",   de: "Das ist etwas teuer. Können Sie günstiger?",  tr: "Biraz pahalı. İndirim yapabilir misiniz?",  pron: "Bi-ras pa-ha-lı. İn-di-rim ja-pa-bi-lir mi-si-nis" },
      { speaker: "B", role: "Verkäufer", de: "Für Sie, ein Euro fünfzig.",                  tr: "Sizin için bir buçuk euro.",                pron: "Si-sin i-tschin bir bu-tschuk eu-ro" },
      { speaker: "A", role: "Tourist",   de: "Gut, ich nehme zwei Kilo.",                   tr: "Tamam, iki kilo alıyorum.",                 pron: "Ta-mam, i-ki ki-lo a-lı-jo-rum" },
      { speaker: "B", role: "Verkäufer", de: "Sonst noch etwas?",                           tr: "Başka bir şey?",                           pron: "Basch-ka bir schej" },
      { speaker: "A", role: "Tourist",   de: "Nein danke, das ist alles.",                  tr: "Hayır teşekkürler, bu kadar.",              pron: "Ha-jır te-schek-kjür-ler, bu ka-dar" },
      { speaker: "B", role: "Verkäufer", de: "Auf Wiedersehen!",                            tr: "İyi günler!",                              pron: "İyi gjün-ler" },
    ],
  },
  {
    id: "taxi",
    title: "Mit dem Taxi fahren",
    emoji: "🚕",
    sub: "Takside",
    lines: [
      { speaker: "A", role: "Tourist", de: "Hallo! Zum Flughafen, bitte.",               tr: "Merhaba! Havalimanına, lütfen.",           pron: "Mer-ha-ba! Ha-wa-li-ma-nı-na, ljüt-fen" },
      { speaker: "B", role: "Fahrer",  de: "Natürlich. Terminal zwei?",                  tr: "Tabii. İkinci terminal mi?",               pron: "Ta-bi-i. İ-kin-dshi ter-mi-nal mi" },
      { speaker: "A", role: "Tourist", de: "Ja. Wie lange dauert es?",                   tr: "Evet. Ne kadar sürer?",                    pron: "E-wet. Ne ka-dar sjü-rer" },
      { speaker: "B", role: "Fahrer",  de: "Ungefähr eine halbe Stunde.",                tr: "Yaklaşık yarım saat.",                     pron: "Jak-la-schık ja-rım sa-at" },
      { speaker: "A", role: "Tourist", de: "Was kostet das ungefähr?",                   tr: "Yaklaşık ne kadar tutar?",                 pron: "Jak-la-schık ne ka-dar tu-tar" },
      { speaker: "B", role: "Fahrer",  de: "Ungefähr vierzig Euro.",                     tr: "Kırk euro civarı.",                        pron: "Kırk eu-ro dschi-wa-rı" },
      { speaker: "A", role: "Tourist", de: "In Ordnung.",                                tr: "Tamam.",                                   pron: "Ta-mam" },
      { speaker: "A", role: "Tourist", de: "Halten Sie hier bitte. Stimmt so.",          tr: "Burada durun, lütfen. Üstü kalsın.",       pron: "Bu-ra-da du-run, ljüt-fen. Üs-tü kal-sın" },
      { speaker: "B", role: "Fahrer",  de: "Vielen Dank! Gute Reise!",                  tr: "Çok teşekkürler! İyi yolculuklar!",        pron: "Tschok te-schek-kjür-ler! İyi jol-dschu-luk-lar" },
    ],
  },
  {
    id: "strand",
    title: "Am Strand / Pool",
    emoji: "🏖️",
    sub: "Sahilde",
    lines: [
      { speaker: "A", role: "Tourist",  de: "Entschuldigung, sind diese Liegestühle frei?",  tr: "Affedersiniz, bu şezlonglar boş mu?",      pron: "Af-fe-der-si-nis, bu sches-long-lar bosch mu" },
      { speaker: "B", role: "Personal", de: "Ja, bitte sehr!",                                tr: "Evet, buyurun!",                            pron: "E-wet, bu-ju-run" },
      { speaker: "A", role: "Tourist",  de: "Danke. Wie viel für den Tag?",                   tr: "Teşekkürler. Günlük ne kadar?",             pron: "Te-schek-kjür-ler. Gjün-ljük ne ka-dar" },
      { speaker: "B", role: "Personal", de: "Zehn Euro pro Liegestuhl.",                      tr: "Şezlong başına on euro.",                   pron: "Sches-long ba-schı-na on eu-ro" },
      { speaker: "A", role: "Tourist",  de: "Gut. Können Sie ein kaltes Wasser bringen?",     tr: "Tamam. Soğuk bir su getirebilir misiniz?",  pron: "Ta-mam. So-uk bir su ge-ti-re-bi-lir mi-si-nis" },
      { speaker: "B", role: "Personal", de: "Natürlich! Ich bringe es sofort.",               tr: "Tabii ki! Hemen getiriyorum.",              pron: "Ta-bi-i ki! He-men ge-ti-ri-jo-rum" },
      { speaker: "A", role: "Tourist",  de: "Haben Sie auch Sonnencreme?",                    tr: "Güneş kreminiz de var mı?",                 pron: "Gjü-nesch kre-mi-nis de war mı" },
      { speaker: "B", role: "Personal", de: "Ja, welchen Schutzfaktor möchten Sie?",          tr: "Evet, hangi faktörü istersiniz?",           pron: "E-wet, han-gi fak-tö-rü is-ter-si-nis" },
      { speaker: "A", role: "Tourist",  de: "SPF 50, bitte.",                                 tr: "Elli faktör, lütfen.",                      pron: "El-li fak-tör, ljüt-fen" },
      { speaker: "B", role: "Personal", de: "Gerne. Viel Spaß!",                              tr: "Tabii. İyi eğlenceler!",                    pron: "Ta-bi-i. İyi e-len-dsche-ler" },
    ],
  },
];
