const DIALOGUES = [
  {
    id: "hotel",
    title: "Im Hotel einchecken",
    titleEn: "Checking in at the hotel",
    emoji: "🏨",
    sub: "Otele Giriş",
    lines: [
      { speaker: "A", role: "Tourist",        roleEn: "Tourist",         de: "Guten Tag, ich habe eine Reservierung.", en: "Good day, I have a reservation.", tr: "İyi günler, rezervasyonum var.",          pron: "İyi gjün-ler, re-ser-was-jo-num war" },
      { speaker: "B", role: "Rezeptionist",   roleEn: "Receptionist",    de: "Ihr Name, bitte?",                       en: "Your name, please?",              tr: "İsminiz, lütfen?",                         pron: "İs-mi-nis, ljüt-fen" },
      { speaker: "A", role: "Tourist",        roleEn: "Tourist",         de: "Schmidt.",                                en: "Schmidt.",                         tr: "Schmidt.",                                  pron: "Schmidt" },
      { speaker: "B", role: "Rezeptionist",   roleEn: "Receptionist",    de: "Ja, fünf Nächte, Doppelzimmer.",         en: "Yes, five nights, double room.",  tr: "Evet, beş gecelik çift kişilik oda.",       pron: "E-wet, besch ge-dsche-lik tschift ki-schi-lik o-da" },
      { speaker: "A", role: "Tourist",        roleEn: "Tourist",         de: "Ist das Frühstück inklusive?",            en: "Is breakfast included?",          tr: "Kahvaltı dahil mi?",                        pron: "Kah-wal-tı da-hil mi" },
      { speaker: "B", role: "Rezeptionist",   roleEn: "Receptionist",    de: "Ja, Frühstück von 7 bis 10 Uhr.",        en: "Yes, breakfast from 7 to 10 am.", tr: "Evet, kahvaltı 7'den 10'a kadar.",          pron: "E-wet, kah-wal-tı je-di-den o-na ka-dar" },
      { speaker: "A", role: "Tourist",        roleEn: "Tourist",         de: "Danke. Wo ist der Aufzug?",               en: "Thanks. Where is the elevator?",  tr: "Teşekkürler. Asansör nerede?",              pron: "Te-schek-kjür-ler. A-san-sjör ne-re-de" },
      { speaker: "B", role: "Rezeptionist",   roleEn: "Receptionist",    de: "Rechts, neben dem Restaurant.",           en: "On the right, next to the restaurant.", tr: "Sağda, restoranın yanında.",          pron: "Saa-da, res-to-ra-nın ja-nın-da" },
      { speaker: "A", role: "Tourist",        roleEn: "Tourist",         de: "Vielen Dank.",                            en: "Thank you very much.",            tr: "Çok teşekkürler.",                          pron: "Tschok te-schek-kjür-ler" },
      { speaker: "B", role: "Rezeptionist",   roleEn: "Receptionist",    de: "Einen schönen Aufenthalt!",               en: "Enjoy your stay!",                tr: "İyi konaklamalar!",                         pron: "İyi ko-nak-la-ma-lar" },
    ],
  },
  {
    id: "restaurant",
    title: "Im Restaurant bestellen",
    titleEn: "Ordering at the restaurant",
    emoji: "🍽️",
    sub: "Restoranda",
    lines: [
      { speaker: "A", role: "Tourist",  roleEn: "Tourist", de: "Guten Abend. Einen Tisch für zwei?",        en: "Good evening. A table for two?",       tr: "İyi akşamlar. İki kişilik masa var mı?",  pron: "İyi ak-scham-lar. İki ki-schi-lik ma-sa war mı" },
      { speaker: "B", role: "Kellner",  roleEn: "Waiter",  de: "Ja, hier bitte.",                            en: "Yes, right this way.",                 tr: "Evet, buyurun.",                           pron: "E-wet, bu-ju-run" },
      { speaker: "A", role: "Tourist",  roleEn: "Tourist", de: "Danke. Die Speisekarte, bitte.",             en: "Thanks. The menu, please.",            tr: "Teşekkürler. Menü, lütfen.",               pron: "Te-schek-kjür-ler. Me-njü, ljüt-fen" },
      { speaker: "B", role: "Kellner",  roleEn: "Waiter",  de: "Bitte. Was möchten Sie trinken?",            en: "Here you go. What would you like to drink?", tr: "Buyurun. Ne içmek istersiniz?",       pron: "Bu-ju-run. Ne itsch-mek is-ter-si-nis" },
      { speaker: "A", role: "Tourist",  roleEn: "Tourist", de: "Ein Wasser und einen Tee, bitte.",           en: "A water and a tea, please.",           tr: "Bir su ve bir çay, lütfen.",               pron: "Bir su we bir tschaj, ljüt-fen" },
      { speaker: "B", role: "Kellner",  roleEn: "Waiter",  de: "Haben Sie schon gewählt?",                   en: "Have you decided yet?",                tr: "Seçtiniz mi?",                             pron: "Setsch-ti-nis mi" },
      { speaker: "A", role: "Tourist",  roleEn: "Tourist", de: "Ja. Ich nehme den Fisch.",                   en: "Yes. I'll have the fish.",             tr: "Evet. Balık alıyorum.",                    pron: "E-wet. Ba-lık a-lı-jo-rum" },
      { speaker: "B", role: "Kellner",  roleEn: "Waiter",  de: "Sehr gerne. Guten Appetit!",                 en: "Certainly. Enjoy your meal!",          tr: "Tabii ki. Afiyet olsun!",                  pron: "Ta-bi-i ki. A-fi-jet ol-sun" },
      { speaker: "A", role: "Tourist",  roleEn: "Tourist", de: "Es war sehr lecker. Die Rechnung, bitte.",   en: "It was very tasty. The bill, please.", tr: "Çok lezzetliydi. Hesap, lütfen.",          pron: "Tschok les-set-li-di. He-sap, ljüt-fen" },
      { speaker: "B", role: "Kellner",  roleEn: "Waiter",  de: "Natürlich, sofort.",                         en: "Of course, right away.",               tr: "Tabii, hemen.",                            pron: "Ta-bi-i, he-men" },
    ],
  },
  {
    id: "markt",
    title: "Auf dem Markt einkaufen",
    titleEn: "Shopping at the market",
    emoji: "🛒",
    sub: "Çarşıda",
    lines: [
      { speaker: "A", role: "Tourist",   roleEn: "Tourist", de: "Guten Morgen! Wie viel kostet das?",          en: "Good morning! How much does that cost?", tr: "Günaydın! Bu ne kadar?",                   pron: "Gjün-aj-dın! Bu ne ka-dar" },
      { speaker: "B", role: "Verkäufer", roleEn: "Seller",  de: "Zwei Euro das Kilo.",                          en: "Two euros a kilo.",                     tr: "Kilo iki euro.",                            pron: "Ki-lo i-ki eu-ro" },
      { speaker: "A", role: "Tourist",   roleEn: "Tourist", de: "Das ist etwas teuer. Können Sie günstiger?",  en: "That's a bit expensive. Can you go cheaper?", tr: "Biraz pahalı. İndirim yapabilir misiniz?",  pron: "Bi-ras pa-ha-lı. İn-di-rim ja-pa-bi-lir mi-si-nis" },
      { speaker: "B", role: "Verkäufer", roleEn: "Seller",  de: "Für Sie, ein Euro fünfzig.",                  en: "For you, one euro fifty.",              tr: "Sizin için bir buçuk euro.",                pron: "Si-sin i-tschin bir bu-tschuk eu-ro" },
      { speaker: "A", role: "Tourist",   roleEn: "Tourist", de: "Gut, ich nehme zwei Kilo.",                   en: "Good, I'll take two kilos.",            tr: "Tamam, iki kilo alıyorum.",                 pron: "Ta-mam, i-ki ki-lo a-lı-jo-rum" },
      { speaker: "B", role: "Verkäufer", roleEn: "Seller",  de: "Sonst noch etwas?",                           en: "Anything else?",                        tr: "Başka bir şey?",                           pron: "Basch-ka bir schej" },
      { speaker: "A", role: "Tourist",   roleEn: "Tourist", de: "Nein danke, das ist alles.",                  en: "No thanks, that's everything.",         tr: "Hayır teşekkürler, bu kadar.",              pron: "Ha-jır te-schek-kjür-ler, bu ka-dar" },
      { speaker: "B", role: "Verkäufer", roleEn: "Seller",  de: "Auf Wiedersehen!",                            en: "Goodbye!",                              tr: "İyi günler!",                              pron: "İyi gjün-ler" },
    ],
  },
  {
    id: "taxi",
    title: "Mit dem Taxi fahren",
    titleEn: "Taking a taxi",
    emoji: "🚕",
    sub: "Takside",
    lines: [
      { speaker: "A", role: "Tourist", roleEn: "Tourist", de: "Hallo! Zum Flughafen, bitte.",               en: "Hello! To the airport, please.",         tr: "Merhaba! Havalimanına, lütfen.",           pron: "Mer-ha-ba! Ha-wa-li-ma-nı-na, ljüt-fen" },
      { speaker: "B", role: "Fahrer",  roleEn: "Driver",  de: "Natürlich. Terminal zwei?",                  en: "Of course. Terminal two?",               tr: "Tabii. İkinci terminal mi?",               pron: "Ta-bi-i. İ-kin-dshi ter-mi-nal mi" },
      { speaker: "A", role: "Tourist", roleEn: "Tourist", de: "Ja. Wie lange dauert es?",                   en: "Yes. How long does it take?",            tr: "Evet. Ne kadar sürer?",                    pron: "E-wet. Ne ka-dar sjü-rer" },
      { speaker: "B", role: "Fahrer",  roleEn: "Driver",  de: "Ungefähr eine halbe Stunde.",                en: "About half an hour.",                    tr: "Yaklaşık yarım saat.",                     pron: "Jak-la-schık ja-rım sa-at" },
      { speaker: "A", role: "Tourist", roleEn: "Tourist", de: "Was kostet das ungefähr?",                   en: "About how much does that cost?",         tr: "Yaklaşık ne kadar tutar?",                 pron: "Jak-la-schık ne ka-dar tu-tar" },
      { speaker: "B", role: "Fahrer",  roleEn: "Driver",  de: "Ungefähr vierzig Euro.",                     en: "About forty euros.",                     tr: "Kırk euro civarı.",                        pron: "Kırk eu-ro dschi-wa-rı" },
      { speaker: "A", role: "Tourist", roleEn: "Tourist", de: "In Ordnung.",                                en: "Alright.",                               tr: "Tamam.",                                   pron: "Ta-mam" },
      { speaker: "A", role: "Tourist", roleEn: "Tourist", de: "Halten Sie hier bitte. Stimmt so.",          en: "Please stop here. Keep the change.",     tr: "Burada durun, lütfen. Üstü kalsın.",       pron: "Bu-ra-da du-run, ljüt-fen. Üs-tü kal-sın" },
      { speaker: "B", role: "Fahrer",  roleEn: "Driver",  de: "Vielen Dank! Gute Reise!",                  en: "Thank you very much! Have a good trip!", tr: "Çok teşekkürler! İyi yolculuklar!",        pron: "Tschok te-schek-kjür-ler! İyi jol-dschu-luk-lar" },
    ],
  },
  {
    id: "strand",
    title: "Am Strand / Pool",
    titleEn: "At the beach / pool",
    emoji: "🏖️",
    sub: "Sahilde",
    lines: [
      { speaker: "A", role: "Tourist",  roleEn: "Tourist", de: "Entschuldigung, sind diese Liegestühle frei?",  en: "Excuse me, are these sun loungers free?", tr: "Affedersiniz, bu şezlonglar boş mu?",      pron: "Af-fe-der-si-nis, bu sches-long-lar bosch mu" },
      { speaker: "B", role: "Personal", roleEn: "Staff",   de: "Ja, bitte sehr!",                                en: "Yes, go ahead!",                          tr: "Evet, buyurun!",                            pron: "E-wet, bu-ju-run" },
      { speaker: "A", role: "Tourist",  roleEn: "Tourist", de: "Danke. Wie viel für den Tag?",                   en: "Thanks. How much for the day?",           tr: "Teşekkürler. Günlük ne kadar?",             pron: "Te-schek-kjür-ler. Gjün-ljük ne ka-dar" },
      { speaker: "B", role: "Personal", roleEn: "Staff",   de: "Zehn Euro pro Liegestuhl.",                      en: "Ten euros per lounger.",                  tr: "Şezlong başına on euro.",                   pron: "Sches-long ba-schı-na on eu-ro" },
      { speaker: "A", role: "Tourist",  roleEn: "Tourist", de: "Gut. Können Sie ein kaltes Wasser bringen?",     en: "Good. Can you bring a cold water?",       tr: "Tamam. Soğuk bir su getirebilir misiniz?",  pron: "Ta-mam. So-uk bir su ge-ti-re-bi-lir mi-si-nis" },
      { speaker: "B", role: "Personal", roleEn: "Staff",   de: "Natürlich! Ich bringe es sofort.",               en: "Of course! I'll bring it right away.",    tr: "Tabii ki! Hemen getiriyorum.",              pron: "Ta-bi-i ki! He-men ge-ti-ri-jo-rum" },
      { speaker: "A", role: "Tourist",  roleEn: "Tourist", de: "Haben Sie auch Sonnencreme?",                    en: "Do you also have sunscreen?",             tr: "Güneş kreminiz de var mı?",                 pron: "Gjü-nesch kre-mi-nis de war mı" },
      { speaker: "B", role: "Personal", roleEn: "Staff",   de: "Ja, welchen Schutzfaktor möchten Sie?",          en: "Yes, what SPF would you like?",           tr: "Evet, hangi faktörü istersiniz?",           pron: "E-wet, han-gi fak-tö-rü is-ter-si-nis" },
      { speaker: "A", role: "Tourist",  roleEn: "Tourist", de: "SPF 50, bitte.",                                 en: "SPF 50, please.",                         tr: "Elli faktör, lütfen.",                      pron: "El-li fak-tör, ljüt-fen" },
      { speaker: "B", role: "Personal", roleEn: "Staff",   de: "Gerne. Viel Spaß!",                              en: "Sure. Have fun!",                         tr: "Tabii. İyi eğlenceler!",                    pron: "Ta-bi-i. İyi e-len-dsche-ler" },
    ],
  },
];
