const VOCABULARY = [
  // ─── BEGRÜSSUNGEN & BASICS ───────────────────────────────────────────────
  { id: 1,  de: "Hallo",                  en: "Hello", tr: "Merhaba",              pron: "Mer-ha-ba",             cat: "basics",   sub: "Begrüßungen" },
  { id: 2,  de: "Guten Morgen",           en: "Good morning", tr: "Günaydın",             pron: "Gjün-aj-dın",           cat: "basics",   sub: "Begrüßungen" },
  { id: 3,  de: "Guten Tag",              en: "Good day", tr: "İyi günler",           pron: "İyi gjün-ler",          cat: "basics",   sub: "Begrüßungen" },
  { id: 4,  de: "Guten Abend",            en: "Good evening", tr: "İyi akşamlar",         pron: "İyi ak-scham-lar",      cat: "basics",   sub: "Begrüßungen" },
  { id: 5,  de: "Gute Nacht",             en: "Good night", tr: "İyi geceler",          pron: "İyi ge-dsche-ler",      cat: "basics",   sub: "Begrüßungen" },
  { id: 6,  de: "Auf Wiedersehen",        en: "Goodbye", tr: "Hoşça kalın",          pron: "Hosch-tscha ka-lın",    cat: "basics",   sub: "Begrüßungen" },
  { id: 7,  de: "Tschüss",               en: "Bye", tr: "Görüşürüz",            pron: "Gjö-rü-schü-rüs",       cat: "basics",   sub: "Begrüßungen" },
  { id: 8,  de: "Bitte",                  en: "Please", tr: "Lütfen",               pron: "Ljüt-fen",              cat: "basics",   sub: "Begrüßungen" },
  { id: 9,  de: "Danke",                  en: "Thank you", tr: "Teşekkür ederim",      pron: "Te-schek-kjür e-de-rim",cat: "basics",   sub: "Begrüßungen" },
  { id: 10, de: "Danke schön",            en: "Thank you very much", tr: "Çok teşekkürler",      pron: "Tschok te-schek-kjür-ler", cat: "basics", sub: "Begrüßungen" },
  { id: 11, de: "Bitte sehr / Gern geschehen", en: "You're welcome", tr: "Rica ederim",     pron: "Ri-dscha e-de-rim",     cat: "basics",   sub: "Begrüßungen" },
  { id: 12, de: "Entschuldigung",         en: "Excuse me / Sorry", tr: "Özür dilerim",         pron: "Ö-sjür di-le-rim",      cat: "basics",   sub: "Begrüßungen" },
  { id: 13, de: "Ja",                     en: "Yes", tr: "Evet",                 pron: "E-wet",                 cat: "basics",   sub: "Begrüßungen" },
  { id: 14, de: "Nein",                   en: "No", tr: "Hayır",                pron: "Ha-jır",                cat: "basics",   sub: "Begrüßungen" },
  { id: 15, de: "Wie geht es Ihnen?",     en: "How are you?", tr: "Nasılsınız?",          pron: "Na-sıl-sı-nıs",         cat: "basics",   sub: "Begrüßungen" },
  { id: 16, de: "Mir geht es gut.",       en: "I'm fine, thank you.", tr: "İyiyim, teşekkürler.", pron: "İ-yi-jim, te-schek-kjür-ler", cat: "basics", sub: "Begrüßungen" },
  { id: 17, de: "Ich verstehe nicht.",    en: "I don't understand.", tr: "Anlamıyorum.",         pron: "An-la-mı-jo-rum",       cat: "basics",   sub: "Begrüßungen" },
  { id: 18, de: "Sprechen Sie Deutsch?",  en: "Do you speak German?", tr: "Almanca biliyor musunuz?", pron: "Al-man-dscha bi-li-jor mu-su-nus", cat: "basics", sub: "Begrüßungen" },

  // ─── ZAHLEN ─────────────────────────────────────────────────────────────
  { id: 20, de: "0 – null",               en: "0 – zero", tr: "sıfır",                pron: "sı-fır",                cat: "basics",   sub: "Zahlen" },
  { id: 21, de: "1 – eins",               en: "1 – one", tr: "bir",                  pron: "bir",                   cat: "basics",   sub: "Zahlen" },
  { id: 22, de: "2 – zwei",               en: "2 – two", tr: "iki",                  pron: "i-ki",                  cat: "basics",   sub: "Zahlen" },
  { id: 23, de: "3 – drei",               en: "3 – three", tr: "üç",                   pron: "ütsch",                 cat: "basics",   sub: "Zahlen" },
  { id: 24, de: "4 – vier",               en: "4 – four", tr: "dört",                 pron: "dört",                  cat: "basics",   sub: "Zahlen" },
  { id: 25, de: "5 – fünf",               en: "5 – five", tr: "beş",                  pron: "besch",                 cat: "basics",   sub: "Zahlen" },
  { id: 26, de: "6 – sechs",              en: "6 – six", tr: "altı",                 pron: "al-tı",                 cat: "basics",   sub: "Zahlen" },
  { id: 27, de: "7 – sieben",             en: "7 – seven", tr: "yedi",                 pron: "je-di",                 cat: "basics",   sub: "Zahlen" },
  { id: 28, de: "8 – acht",               en: "8 – eight", tr: "sekiz",                pron: "se-kis",                cat: "basics",   sub: "Zahlen" },
  { id: 29, de: "9 – neun",               en: "9 – nine", tr: "dokuz",                pron: "do-kus",                cat: "basics",   sub: "Zahlen" },
  { id: 30, de: "10 – zehn",              en: "10 – ten", tr: "on",                   pron: "on",                    cat: "basics",   sub: "Zahlen" },
  { id: 31, de: "20 – zwanzig",           en: "20 – twenty", tr: "yirmi",                pron: "jir-mi",                cat: "basics",   sub: "Zahlen" },
  { id: 32, de: "50 – fünfzig",           en: "50 – fifty", tr: "elli",                 pron: "el-li",                 cat: "basics",   sub: "Zahlen" },
  { id: 33, de: "100 – hundert",          en: "100 – hundred", tr: "yüz",                  pron: "jüs",                   cat: "basics",   sub: "Zahlen" },
  { id: 34, de: "1000 – tausend",         en: "1000 – thousand", tr: "bin",                  pron: "bin",                   cat: "basics",   sub: "Zahlen" },

  // ─── WOCHENTAGE & ZEIT ───────────────────────────────────────────────────
  { id: 40, de: "Montag",                 en: "Monday", tr: "Pazartesi",            pron: "Pa-sar-te-si",          cat: "basics",   sub: "Zeit" },
  { id: 41, de: "Dienstag",               en: "Tuesday", tr: "Salı",                 pron: "Sa-lı",                 cat: "basics",   sub: "Zeit" },
  { id: 42, de: "Mittwoch",               en: "Wednesday", tr: "Çarşamba",             pron: "Tschar-scham-ba",       cat: "basics",   sub: "Zeit" },
  { id: 43, de: "Donnerstag",             en: "Thursday", tr: "Perşembe",             pron: "Per-schem-be",          cat: "basics",   sub: "Zeit" },
  { id: 44, de: "Freitag",                en: "Friday", tr: "Cuma",                 pron: "Dschu-ma",              cat: "basics",   sub: "Zeit" },
  { id: 45, de: "Samstag",                en: "Saturday", tr: "Cumartesi",            pron: "Dschu-mar-te-si",       cat: "basics",   sub: "Zeit" },
  { id: 46, de: "Sonntag",                en: "Sunday", tr: "Pazar",                pron: "Pa-sar",                cat: "basics",   sub: "Zeit" },
  { id: 47, de: "heute",                  en: "today", tr: "bugün",                pron: "bu-gjün",               cat: "basics",   sub: "Zeit" },
  { id: 48, de: "morgen",                 en: "tomorrow", tr: "yarın",                pron: "ja-rın",                cat: "basics",   sub: "Zeit" },
  { id: 49, de: "gestern",                en: "yesterday", tr: "dün",                  pron: "djün",                  cat: "basics",   sub: "Zeit" },
  { id: 50, de: "Wie spät ist es?",       en: "What time is it?", tr: "Saat kaç?",            pron: "Sa-at katsch",          cat: "basics",   sub: "Zeit" },

  // ─── HOTEL ──────────────────────────────────────────────────────────────
  { id: 60, de: "Ich habe eine Reservierung.", en: "I have a reservation.", tr: "Rezervasyonum var.", pron: "Re-ser-was-jo-num war", cat: "urlaub", sub: "Hotel" },
  { id: 61, de: "Ein Zimmer für zwei Personen", en: "A room for two people", tr: "İki kişilik bir oda",  pron: "İki ki-schi-lik bir o-da", cat: "urlaub", sub: "Hotel" },
  { id: 62, de: "Doppelzimmer",           en: "Double room", tr: "çift kişilik oda",     pron: "tschift ki-schi-lik o-da", cat: "urlaub", sub: "Hotel" },
  { id: 63, de: "Einzelzimmer",           en: "Single room", tr: "tek kişilik oda",      pron: "tek ki-schi-lik o-da",  cat: "urlaub", sub: "Hotel" },
  { id: 64, de: "Frühstück inklusive?",   en: "Is breakfast included?", tr: "Kahvaltı dahil mi?",   pron: "Kah-wal-tı da-hil mi",  cat: "urlaub", sub: "Hotel" },
  { id: 65, de: "Wann ist Check-out?",    en: "When is check-out?", tr: "Check-out saati ne zaman?", pron: "Tschek-aut sa-a-ti ne sa-man", cat: "urlaub", sub: "Hotel" },
  { id: 66, de: "Der Schlüssel",          en: "The key", tr: "Anahtar",              pron: "An-ah-tar",             cat: "urlaub", sub: "Hotel" },
  { id: 67, de: "Das Handtuch",           en: "The towel", tr: "Havlu",                pron: "Haw-lu",                cat: "urlaub", sub: "Hotel" },
  { id: 68, de: "Das Zimmer ist nicht sauber.", en: "The room isn't clean.", tr: "Oda temiz değil.", pron: "O-da te-mis de-jil",  cat: "urlaub", sub: "Hotel" },
  { id: 69, de: "Haben Sie WLAN?",        en: "Do you have WiFi?", tr: "Wi-Fi var mı?",        pron: "Waj-faj war mı",        cat: "urlaub", sub: "Hotel" },
  { id: 70, de: "Ich möchte auschecken.", en: "I would like to check out.", tr: "Check-out yapmak istiyorum.", pron: "Tschek-aut jap-mak is-ti-jo-rum", cat: "urlaub", sub: "Hotel" },

  // ─── RESTAURANT & ESSEN ──────────────────────────────────────────────────
  { id: 80, de: "Einen Tisch für zwei, bitte.", en: "A table for two, please.", tr: "İki kişilik masa, lütfen.", pron: "İki ki-schi-lik ma-sa, ljüt-fen", cat: "urlaub", sub: "Restaurant" },
  { id: 81, de: "Die Speisekarte, bitte.",  en: "The menu, please.", tr: "Menü, lütfen.",        pron: "Me-njü, ljüt-fen",      cat: "urlaub", sub: "Restaurant" },
  { id: 82, de: "Was empfehlen Sie?",      en: "What do you recommend?", tr: "Ne tavsiye edersiniz?", pron: "Ne taw-si-je e-der-si-nis", cat: "urlaub", sub: "Restaurant" },
  { id: 83, de: "Ich bin Vegetarier.",     en: "I'm a vegetarian.", tr: "Ben vejeteryenim.",    pron: "Ben we-dsche-ter-ja-nim", cat: "urlaub", sub: "Restaurant" },
  { id: 84, de: "Ohne Fleisch, bitte.",    en: "Without meat, please.", tr: "Etsiz, lütfen.",       pron: "Et-sis, ljüt-fen",      cat: "urlaub", sub: "Restaurant" },
  { id: 85, de: "Die Rechnung, bitte.",    en: "The bill, please.", tr: "Hesap, lütfen.",       pron: "He-sap, ljüt-fen",      cat: "urlaub", sub: "Restaurant" },
  { id: 86, de: "Es hat sehr gut geschmeckt.", en: "It tasted very good.", tr: "Çok lezzetliydi.", pron: "Tschok les-set-li-di",  cat: "urlaub", sub: "Restaurant" },
  { id: 87, de: "Wasser",                  en: "Water", tr: "Su",                   pron: "su",                    cat: "urlaub", sub: "Restaurant" },
  { id: 88, de: "Tee",                     en: "Tea", tr: "Çay",                  pron: "tschaj",                cat: "urlaub", sub: "Restaurant" },
  { id: 89, de: "Kaffee",                  en: "Coffee", tr: "Kahve",                pron: "kah-we",                cat: "urlaub", sub: "Restaurant" },
  { id: 90, de: "Brot",                    en: "Bread", tr: "Ekmek",                pron: "ek-mek",                cat: "urlaub", sub: "Restaurant" },
  { id: 91, de: "Fleisch",                 en: "Meat", tr: "Et",                   pron: "et",                    cat: "urlaub", sub: "Restaurant" },
  { id: 92, de: "Fisch",                   en: "Fish", tr: "Balık",                pron: "ba-lık",                cat: "urlaub", sub: "Restaurant" },
  { id: 93, de: "Gemüse",                  en: "Vegetables", tr: "Sebze",                pron: "seb-se",                cat: "urlaub", sub: "Restaurant" },
  { id: 94, de: "lecker / köstlich",       en: "tasty / delicious", tr: "lezzetli",             pron: "les-set-li",            cat: "urlaub", sub: "Restaurant" },
  { id: 95, de: "Guten Appetit!",          en: "Enjoy your meal!", tr: "Afiyet olsun!",        pron: "A-fi-jet ol-sun",       cat: "urlaub", sub: "Restaurant" },

  // ─── STRAND & FREIZEIT ───────────────────────────────────────────────────
  { id: 100, de: "Das Meer",              en: "The sea", tr: "Deniz",                 pron: "De-nis",                cat: "urlaub", sub: "Strand" },
  { id: 101, de: "Der Strand",            en: "The beach", tr: "Sahil / Plaj",         pron: "Sa-hil / Pladsch",      cat: "urlaub", sub: "Strand" },
  { id: 102, de: "Wo ist das Meer?",      en: "Where is the sea?", tr: "Deniz nerede?",        pron: "De-nis ne-re-de",       cat: "urlaub", sub: "Strand" },
  { id: 103, de: "Sonnencreme",           en: "Sunscreen", tr: "Güneş kremi",          pron: "Gjü-nesch kre-mi",      cat: "urlaub", sub: "Strand" },
  { id: 104, de: "Liegestuhl",            en: "Sun lounger", tr: "Şezlong",              pron: "Sches-long",            cat: "urlaub", sub: "Strand" },
  { id: 105, de: "Sonnenschirm",          en: "Sun umbrella", tr: "Şemsiye",              pron: "Schem-si-je",           cat: "urlaub", sub: "Strand" },
  { id: 106, de: "schwimmen",             en: "to swim", tr: "yüzmek",               pron: "jüs-mek",               cat: "urlaub", sub: "Strand" },
  { id: 107, de: "Das Schwimmbad",        en: "The swimming pool", tr: "Yüzme havuzu",         pron: "Jüs-me ha-wu-su",       cat: "urlaub", sub: "Strand" },
  { id: 108, de: "Es ist heiß.",          en: "It's hot.", tr: "Hava çok sıcak.",      pron: "Ha-wa tschok sı-dschak", cat: "urlaub", sub: "Strand" },

  // ─── EINKAUFEN & MARKT ───────────────────────────────────────────────────
  { id: 110, de: "Wie viel kostet das?",  en: "How much does that cost?", tr: "Bu ne kadar?",         pron: "Bu ne ka-dar",          cat: "urlaub", sub: "Einkaufen" },
  { id: 111, de: "Das ist zu teuer.",     en: "That's too expensive.", tr: "Bu çok pahalı.",       pron: "Bu tschok pa-ha-lı",    cat: "urlaub", sub: "Einkaufen" },
  { id: 112, de: "Haben Sie etwas Günstigeres?", en: "Do you have something cheaper?", tr: "Daha ucuzu var mı?", pron: "Da-ha u-dschu-su war mı", cat: "urlaub", sub: "Einkaufen" },
  { id: 113, de: "Ich nehme das.",        en: "I'll take that.", tr: "Bunu alıyorum.",       pron: "Bu-nu a-lı-jo-rum",     cat: "urlaub", sub: "Einkaufen" },
  { id: 114, de: "Wo ist der Markt?",     en: "Where is the market?", tr: "Çarşı nerede?",        pron: "Tschar-schı ne-re-de",  cat: "urlaub", sub: "Einkaufen" },
  { id: 115, de: "Bargeld",               en: "Cash", tr: "Nakit",                pron: "Na-kit",                cat: "urlaub", sub: "Einkaufen" },
  { id: 116, de: "Kreditkarte",           en: "Credit card", tr: "Kredi kartı",          pron: "Kre-di kar-tı",         cat: "urlaub", sub: "Einkaufen" },
  { id: 117, de: "Tüte / Beutel",         en: "Bag", tr: "Poşet",                pron: "Po-schet",              cat: "urlaub", sub: "Einkaufen" },
  { id: 118, de: "Wo ist der Supermarkt?", en: "Where is the supermarket?", tr: "Süpermarket nerede?", pron: "Sjü-per-mar-ket ne-re-de", cat: "urlaub", sub: "Einkaufen" },

  // ─── TRANSPORT ───────────────────────────────────────────────────────────
  { id: 120, de: "Wo ist der Bahnhof?",   en: "Where is the train station?", tr: "Tren garı nerede?",    pron: "Tren ga-rı ne-re-de",   cat: "urlaub", sub: "Transport" },
  { id: 121, de: "Wo ist der Flughafen?", en: "Where is the airport?", tr: "Havalimanı nerede?",   pron: "Ha-wa-li-ma-nı ne-re-de", cat: "urlaub", sub: "Transport" },
  { id: 122, de: "Ein Ticket nach Istanbul", en: "A ticket to Istanbul", tr: "İstanbul'a bir bilet", pron: "İs-tan-bu-la bir bi-let", cat: "urlaub", sub: "Transport" },
  { id: 123, de: "Wann fährt der Bus?",   en: "When does the bus leave?", tr: "Otobüs ne zaman kalkıyor?", pron: "O-to-bjüs ne sa-man kal-kı-jor", cat: "urlaub", sub: "Transport" },
  { id: 124, de: "Taxi!",                 en: "Taxi!", tr: "Taksi!",               pron: "Tak-si",                cat: "urlaub", sub: "Transport" },
  { id: 125, de: "links",                 en: "left", tr: "sol",                  pron: "sol",                   cat: "urlaub", sub: "Transport" },
  { id: 126, de: "rechts",                en: "right", tr: "sağ",                  pron: "saa",                   cat: "urlaub", sub: "Transport" },
  { id: 127, de: "geradeaus",             en: "straight ahead", tr: "düz git",              pron: "djüs git",              cat: "urlaub", sub: "Transport" },
  { id: 128, de: "Halten Sie hier, bitte.", en: "Please stop here.", tr: "Burada durun, lütfen.", pron: "Bu-ra-da du-run, ljüt-fen", cat: "urlaub", sub: "Transport" },

  // ─── NOTFÄLLE ────────────────────────────────────────────────────────────
  { id: 130, de: "Hilfe!",                en: "Help!", tr: "İmdat!",               pron: "İm-dat",                cat: "urlaub", sub: "Notfälle" },
  { id: 131, de: "Arzt / Krankenhaus",    en: "Doctor / Hospital", tr: "Doktor / Hastane",     pron: "Dok-tor / Has-ta-ne",   cat: "urlaub", sub: "Notfälle" },
  { id: 132, de: "Ich brauche einen Arzt.", en: "I need a doctor.", tr: "Doktora ihtiyacım var.", pron: "Dok-to-ra ih-ti-ja-dschım war", cat: "urlaub", sub: "Notfälle" },
  { id: 133, de: "Rufen Sie die Polizei!", en: "Call the police!", tr: "Polisi arayın!",      pron: "Po-li-si a-ra-jın",     cat: "urlaub", sub: "Notfälle" },
  { id: 134, de: "Ich habe meinen Pass verloren.", en: "I lost my passport.", tr: "Pasaportumu kaybettim.", pron: "Pa-sa-por-tu-mu kaj-bet-tim", cat: "urlaub", sub: "Notfälle" },
  { id: 135, de: "Apotheke",              en: "Pharmacy", tr: "Eczane",               pron: "Edsch-sa-ne",           cat: "urlaub", sub: "Notfälle" },

  // ─── HAUSHALT & FAMILIE ──────────────────────────────────────────────────
  { id: 140, de: "Die Familie",           en: "The family", tr: "Aile",                 pron: "A-i-le",                cat: "alltag",  sub: "Familie" },
  { id: 141, de: "Mutter",                en: "Mother", tr: "Anne",                 pron: "An-ne",                 cat: "alltag",  sub: "Familie" },
  { id: 142, de: "Vater",                 en: "Father", pron: "Ba-ba",              tr: "Baba",                    cat: "alltag",  sub: "Familie" },
  { id: 143, de: "Kind / Kinder",         en: "Child / Children", tr: "Çocuk / Çocuklar",    pron: "Tscho-dschuk / Tscho-dschuk-lar", cat: "alltag", sub: "Familie" },
  { id: 144, de: "Bruder",                en: "Brother", tr: "Erkek kardeş",         pron: "Er-kek kar-desch",      cat: "alltag",  sub: "Familie" },
  { id: 145, de: "Schwester",             en: "Sister", tr: "Kız kardeş",           pron: "Kıs kar-desch",         cat: "alltag",  sub: "Familie" },
  { id: 146, de: "Großmutter",            en: "Grandmother", tr: "Büyükanne",            pron: "Bjü-jük-an-ne",         cat: "alltag",  sub: "Familie" },
  { id: 147, de: "Großvater",             en: "Grandfather", tr: "Büyükbaba",            pron: "Bjü-jük-ba-ba",         cat: "alltag",  sub: "Familie" },
  { id: 148, de: "Ehemann",               en: "Husband", tr: "Koca / Eş",            pron: "Ko-dscha / Esch",       cat: "alltag",  sub: "Familie" },
  { id: 149, de: "Ehefrau",               en: "Wife", tr: "Karı / Eş",            pron: "Ka-rı / Esch",          cat: "alltag",  sub: "Familie" },

  // ─── HAUSHALT & WOHNEN ───────────────────────────────────────────────────
  { id: 150, de: "Das Haus",              en: "The house", tr: "Ev",                   pron: "ew",                    cat: "alltag",  sub: "Wohnen" },
  { id: 151, de: "Die Küche",             en: "The kitchen", tr: "Mutfak",               pron: "Mut-fak",               cat: "alltag",  sub: "Wohnen" },
  { id: 152, de: "Das Wohnzimmer",        en: "The living room", tr: "Oturma odası",         pron: "O-tur-ma o-da-sı",      cat: "alltag",  sub: "Wohnen" },
  { id: 153, de: "Das Schlafzimmer",      en: "The bedroom", tr: "Yatak odası",          pron: "Ja-tak o-da-sı",        cat: "alltag",  sub: "Wohnen" },
  { id: 154, de: "Das Badezimmer",        en: "The bathroom", tr: "Banyo",                pron: "Ban-jo",                cat: "alltag",  sub: "Wohnen" },
  { id: 155, de: "Wasser",                en: "Water", tr: "Su",                   pron: "su",                    cat: "alltag",  sub: "Wohnen" },
  { id: 156, de: "Das Fenster",           en: "The window", tr: "Pencere",              pron: "Pen-dsche-re",          cat: "alltag",  sub: "Wohnen" },
  { id: 157, de: "Die Tür",               en: "The door", tr: "Kapı",                 pron: "Ka-pı",                 cat: "alltag",  sub: "Wohnen" },
  { id: 158, de: "Das Licht",             en: "The light", tr: "Işık",                 pron: "I-schık",               cat: "alltag",  sub: "Wohnen" },
  { id: 159, de: "Mach das Licht an.",    en: "Turn on the light.", tr: "Işığı aç.",            pron: "I-schı-ı atsch",        cat: "alltag",  sub: "Wohnen" },

  // ─── ALLTAG & KOMMUNIKATION ──────────────────────────────────────────────
  { id: 160, de: "Ich bin müde.",         en: "I'm tired.", tr: "Yorgunum.",            pron: "Jor-gu-num",            cat: "alltag",  sub: "Alltag" },
  { id: 161, de: "Ich habe Hunger.",      en: "I'm hungry.", tr: "Açım.",                pron: "a-tschım",              cat: "alltag",  sub: "Alltag" },
  { id: 162, de: "Ich habe Durst.",       en: "I'm thirsty.", tr: "Susadım.",             pron: "Su-sa-dım",             cat: "alltag",  sub: "Alltag" },
  { id: 163, de: "Was machst du?",        en: "What are you doing?", tr: "Ne yapıyorsun?",       pron: "Ne ja-pı-jor-sun",      cat: "alltag",  sub: "Alltag" },
  { id: 164, de: "Komm her!",             en: "Come here!", tr: "Gel buraya!",          pron: "Gel bu-ra-ja",          cat: "alltag",  sub: "Alltag" },
  { id: 165, de: "Warte kurz!",           en: "Wait a moment!", tr: "Bir dakika!",          pron: "Bir da-ki-ka",          cat: "alltag",  sub: "Alltag" },
  { id: 166, de: "Ich liebe dich.",       en: "I love you.", tr: "Seni seviyorum.",      pron: "Se-ni se-wi-jo-rum",    cat: "alltag",  sub: "Alltag" },
  { id: 167, de: "Schau mal!",            en: "Look!", tr: "Bak şuna!",            pron: "Bak schu-na",           cat: "alltag",  sub: "Alltag" },
  { id: 168, de: "Vorsicht!",             en: "Careful!", tr: "Dikkat!",              pron: "Dik-kat",               cat: "alltag",  sub: "Alltag" },
  { id: 169, de: "Kein Problem.",         en: "No problem.", tr: "Sorun değil.",         pron: "So-run de-jil",         cat: "alltag",  sub: "Alltag" },
  { id: 170, de: "Natürlich!",            en: "Of course!", tr: "Tabii ki!",            pron: "Ta-bi-i ki",            cat: "alltag",  sub: "Alltag" },
  { id: 171, de: "Vielleicht.",           en: "Maybe.", tr: "Belki.",               pron: "Bel-ki",                cat: "alltag",  sub: "Alltag" },
  { id: 172, de: "Wann?",                 en: "When?", tr: "Ne zaman?",            pron: "Ne sa-man",             cat: "alltag",  sub: "Alltag" },
  { id: 173, de: "Wo?",                   en: "Where?", tr: "Nerede?",              pron: "Ne-re-de",              cat: "alltag",  sub: "Alltag" },
  { id: 174, de: "Warum?",               en: "Why?", tr: "Neden? / Niye?",       pron: "Ne-den / Ni-je",        cat: "alltag",  sub: "Alltag" },
  { id: 175, de: "Wie?",                  en: "How?", tr: "Nasıl?",               pron: "Na-sıl",                cat: "alltag",  sub: "Alltag" },

  // ─── KÖRPER & GESUNDHEIT ─────────────────────────────────────────────────
  { id: 180, de: "Ich bin krank.",        en: "I'm sick.", tr: "Hastayım.",            pron: "Has-ta-jım",            cat: "alltag",  sub: "Gesundheit" },
  { id: 181, de: "Mir ist schwindelig.",  en: "I feel dizzy.", tr: "Başım dönüyor.",       pron: "Ba-schım dö-njü-jor",   cat: "alltag",  sub: "Gesundheit" },
  { id: 182, de: "Ich habe Schmerzen.",   en: "I'm in pain.", tr: "Ağrım var.",           pron: "Aa-rım war",            cat: "alltag",  sub: "Gesundheit" },
  { id: 183, de: "Kopfschmerzen",         en: "Headache", tr: "Baş ağrısı",           pron: "Basch aa-rı-sı",        cat: "alltag",  sub: "Gesundheit" },
  { id: 184, de: "Magenschmerzen",        en: "Stomachache", tr: "Mide ağrısı",          pron: "Mi-de aa-rı-sı",        cat: "alltag",  sub: "Gesundheit" },
  { id: 185, de: "Ich bin allergisch gegen...", en: "I'm allergic to...", tr: "...ye alerjim var.", pron: "...je a-ler-dschim war", cat: "alltag", sub: "Gesundheit" },

  // ─── ZAHLEN ERWEITERT ────────────────────────────────────────────────────
  { id: 200, de: "11 – elf",               en: "11 – eleven", tr: "on bir",           pron: "on bir",              cat: "basics", sub: "Zahlen" },
  { id: 201, de: "12 – zwölf",             en: "12 – twelve", tr: "on iki",           pron: "on i-ki",             cat: "basics", sub: "Zahlen" },
  { id: 202, de: "13 – dreizehn",          en: "13 – thirteen", tr: "on üç",            pron: "on ütsch",            cat: "basics", sub: "Zahlen" },
  { id: 203, de: "14 – vierzehn",          en: "14 – fourteen", tr: "on dört",          pron: "on dört",             cat: "basics", sub: "Zahlen" },
  { id: 204, de: "15 – fünfzehn",          en: "15 – fifteen", tr: "on beş",           pron: "on besch",            cat: "basics", sub: "Zahlen" },
  { id: 205, de: "16 – sechzehn",          en: "16 – sixteen", tr: "on altı",          pron: "on al-tı",            cat: "basics", sub: "Zahlen" },
  { id: 206, de: "17 – siebzehn",          en: "17 – seventeen", tr: "on yedi",          pron: "on je-di",            cat: "basics", sub: "Zahlen" },
  { id: 207, de: "18 – achtzehn",          en: "18 – eighteen", tr: "on sekiz",         pron: "on se-kis",           cat: "basics", sub: "Zahlen" },
  { id: 208, de: "19 – neunzehn",          en: "19 – nineteen", tr: "on dokuz",         pron: "on do-kus",           cat: "basics", sub: "Zahlen" },
  { id: 209, de: "25 – fünfundzwanzig",    en: "25 – twenty-five", tr: "yirmi beş",        pron: "jir-mi besch",        cat: "basics", sub: "Zahlen" },
  { id: 210, de: "30 – dreißig",           en: "30 – thirty", tr: "otuz",             pron: "o-tus",               cat: "basics", sub: "Zahlen" },
  { id: 211, de: "40 – vierzig",           en: "40 – forty", tr: "kırk",             pron: "kırk",                cat: "basics", sub: "Zahlen" },
  { id: 212, de: "60 – sechzig",           en: "60 – sixty", tr: "altmış",           pron: "alt-mısch",           cat: "basics", sub: "Zahlen" },
  { id: 213, de: "70 – siebzig",           en: "70 – seventy", tr: "yetmiş",           pron: "jet-misch",           cat: "basics", sub: "Zahlen" },
  { id: 214, de: "80 – achtzig",           en: "80 – eighty", tr: "seksen",           pron: "sek-sen",             cat: "basics", sub: "Zahlen" },
  { id: 215, de: "90 – neunzig",           en: "90 – ninety", tr: "doksan",           pron: "dok-san",             cat: "basics", sub: "Zahlen" },
  { id: 216, de: "150 – hundertfünfzig",   en: "150 – one hundred fifty", tr: "yüz elli",         pron: "jüs el-li",           cat: "basics", sub: "Zahlen" },
  { id: 217, de: "200 – zweihundert",      en: "200 – two hundred", tr: "iki yüz",          pron: "i-ki jüs",            cat: "basics", sub: "Zahlen" },
  { id: 218, de: "300 – dreihundert",      en: "300 – three hundred", tr: "üç yüz",           pron: "ütsch jüs",           cat: "basics", sub: "Zahlen" },
  { id: 219, de: "500 – fünfhundert",      en: "500 – five hundred", tr: "beş yüz",          pron: "besch jüs",           cat: "basics", sub: "Zahlen" },
  { id: 220, de: "750 – siebenhundertfünfzig", en: "750 – seven hundred fifty", tr: "yedi yüz elli", pron: "je-di jüs el-li",   cat: "basics", sub: "Zahlen" },
  { id: 221, de: "1.500 – eintausendfünfhundert", en: "1,500 – one thousand five hundred", tr: "bin beş yüz", pron: "bin besch jüs",    cat: "basics", sub: "Zahlen" },
  { id: 222, de: "2.000 – zweitausend",    en: "2,000 – two thousand", tr: "iki bin",          pron: "i-ki bin",            cat: "basics", sub: "Zahlen" },
  { id: 223, de: "5.000 – fünftausend",    en: "5,000 – five thousand", tr: "beş bin",          pron: "besch bin",           cat: "basics", sub: "Zahlen" },
  { id: 224, de: "10.000 – zehntausend",   en: "10,000 – ten thousand", tr: "on bin",           pron: "on bin",              cat: "basics", sub: "Zahlen" },
  { id: 225, de: "eine halbe",             en: "a half", tr: "yarım",            pron: "ja-rım",              cat: "basics", sub: "Zahlen" },
  { id: 226, de: "erste/r/s",             en: "first", tr: "birinci",           pron: "bi-rin-dshi",         cat: "basics", sub: "Zahlen" },
  { id: 227, de: "zweite/r/s",            en: "second", tr: "ikinci",            pron: "i-kin-dshi",          cat: "basics", sub: "Zahlen" },
  { id: 228, de: "dritte/r/s",            en: "third", tr: "üçüncü",            pron: "ü-tschün-dshü",       cat: "basics", sub: "Zahlen" },

  // ─── BEZAHLEN ────────────────────────────────────────────────────────────
  { id: 230, de: "Was macht das insgesamt?",     en: "What's the total?", tr: "Toplam ne kadar?",          pron: "Top-lam ne ka-dar",            cat: "urlaub", sub: "Bezahlen" },
  { id: 231, de: "Das macht 50 Euro.",            en: "That comes to 50 euros.", tr: "Elli euro eder.",            pron: "El-li eu-ro e-der",            cat: "urlaub", sub: "Bezahlen" },
  { id: 232, de: "Nehmen Sie Kreditkarte?",       en: "Do you accept credit card?", tr: "Kredi kartı geçer mi?",      pron: "Kre-di kar-tı ge-tscher mi",   cat: "urlaub", sub: "Bezahlen" },
  { id: 233, de: "Bar oder Karte?",               en: "Cash or card?", tr: "Nakit mi, kart mı?",         pron: "Na-kit mi, kart mı",           cat: "urlaub", sub: "Bezahlen" },
  { id: 234, de: "Stimmt so. (Kein Rest.)",       en: "Keep the change.", tr: "Üstü kalsın.",               pron: "Üs-tü kal-sın",               cat: "urlaub", sub: "Bezahlen" },
  { id: 235, de: "Das Wechselgeld",               en: "The change", tr: "Para üstü",                  pron: "Pa-ra üs-tü",                  cat: "urlaub", sub: "Bezahlen" },
  { id: 236, de: "Kleingeld",                     en: "Small change / coins", tr: "Bozuk para",                 pron: "Bo-suk pa-ra",                 cat: "urlaub", sub: "Bezahlen" },
  { id: 237, de: "Haben Sie Kleingeld?",          en: "Do you have change?", tr: "Bozuk paranız var mı?",      pron: "Bo-suk pa-ra-nıs war mı",     cat: "urlaub", sub: "Bezahlen" },
  { id: 238, de: "Die Quittung / Der Bon",        en: "The receipt", tr: "Fiş / Makbuz",               pron: "Fisch / Mak-bus",              cat: "urlaub", sub: "Bezahlen" },
  { id: 239, de: "Quittung bitte.",               en: "Receipt please.", tr: "Fiş lütfen.",                pron: "Fisch ljüt-fen",               cat: "urlaub", sub: "Bezahlen" },
  { id: 240, de: "Kostenlos / Gratis",            en: "Free of charge", tr: "Ücretsiz / Bedava",          pron: "Üdsch-ret-sis / Be-da-wa",     cat: "urlaub", sub: "Bezahlen" },
  { id: 241, de: "Gibt es Rabatt?",               en: "Is there a discount?", tr: "İndirim var mı?",            pron: "İn-di-rim war mı",             cat: "urlaub", sub: "Bezahlen" },
  { id: 242, de: "Ich habe kein Bargeld.",        en: "I don't have cash.", tr: "Nakit param yok.",           pron: "Na-kit pa-ram jok",            cat: "urlaub", sub: "Bezahlen" },
  { id: 243, de: "Zu teuer.",                     en: "Too expensive.", tr: "Çok pahalı.",                pron: "Tschok pa-ha-lı",              cat: "urlaub", sub: "Bezahlen" },
  { id: 244, de: "Der Preis / Was kostet das?",   en: "The price / How much does it cost?", tr: "Fiyat / Fiyatı ne kadar?",  pron: "Fi-jat / Fi-ja-tı ne ka-dar", cat: "urlaub", sub: "Bezahlen" },
  { id: 245, de: "Getrennt bezahlen.",            en: "Pay separately.", tr: "Ayrı ayrı ödeyeceğiz.",      pron: "Aj-rı aj-rı ö-de-je-dshis",  cat: "urlaub", sub: "Bezahlen" },
  { id: 246, de: "Zusammen bezahlen.",            en: "Pay together.", tr: "Birlikte ödeyeceğiz.",       pron: "Bir-lik-te ö-de-je-dshis",    cat: "urlaub", sub: "Bezahlen" },

  // ─── PRAKTISCHE SÄTZE ────────────────────────────────────────────────────
  { id: 250, de: "Geht das? / Ist das möglich?", en: "Is that possible?", tr: "Olur mu?",                   pron: "O-lur mu",                     cat: "basics", sub: "Praktisch" },
  { id: 251, de: "Nicht möglich / Geht nicht.",  en: "Not possible.", tr: "Olmaz.",                     pron: "Ol-mas",                       cat: "basics", sub: "Praktisch" },
  { id: 252, de: "Ich weiß nicht.",              en: "I don't know.", tr: "Bilmiyorum.",                 pron: "Bil-mi-jo-rum",                cat: "basics", sub: "Praktisch" },
  { id: 253, de: "Ich habe verstanden.",         en: "I understood.", tr: "Anladım.",                    pron: "An-la-dım",                    cat: "basics", sub: "Praktisch" },
  { id: 254, de: "Langsamer, bitte.",            en: "Slower, please.", tr: "Daha yavaş, lütfen.",         pron: "Da-ha ja-wasch, ljüt-fen",     cat: "basics", sub: "Praktisch" },
  { id: 255, de: "Können Sie das aufschreiben?", en: "Can you write that down?", tr: "Yazabilir misiniz?",          pron: "Ja-sa-bi-lir mi-si-nis",       cat: "basics", sub: "Praktisch" },
  { id: 256, de: "Wie heißen Sie?",             en: "What is your name?", tr: "Adınız ne?",                  pron: "A-dı-nıs ne",                  cat: "basics", sub: "Praktisch" },
  { id: 257, de: "Ich heiße ...",               en: "My name is ...", tr: "Adım ...",                    pron: "A-dım",                        cat: "basics", sub: "Praktisch" },
  { id: 258, de: "Woher kommen Sie?",           en: "Where are you from?", tr: "Nerelisiniz?",                pron: "Ne-re-li-si-nis",              cat: "basics", sub: "Praktisch" },
  { id: 259, de: "Ich komme aus Deutschland.",  en: "I'm from Germany.", tr: "Almanya'danım.",              pron: "Al-man-ja-da-nım",             cat: "basics", sub: "Praktisch" },
  { id: 260, de: "Ich suche ...",               en: "I'm looking for ...", tr: "... arıyorum.",               pron: "a-rı-jo-rum",                  cat: "basics", sub: "Praktisch" },
  { id: 261, de: "Gibt es hier ...?",           en: "Is there ... here?", tr: "Burada ... var mı?",          pron: "Bu-ra-da ... war mı",          cat: "basics", sub: "Praktisch" },
  { id: 262, de: "Wie weit ist es?",            en: "How far is it?", tr: "Ne kadar uzak?",              pron: "Ne ka-dar u-sak",              cat: "basics", sub: "Praktisch" },
  { id: 263, de: "Offen / Geöffnet",            en: "Open", tr: "Açık",                        pron: "A-tschık",                     cat: "basics", sub: "Praktisch" },
  { id: 264, de: "Geschlossen",                 en: "Closed", tr: "Kapalı",                      pron: "Ka-pa-lı",                     cat: "basics", sub: "Praktisch" },
  { id: 265, de: "Wann öffnet es?",             en: "When does it open?", tr: "Ne zaman açılıyor?",          pron: "Ne sa-man a-tschı-lı-jor",    cat: "basics", sub: "Praktisch" },
  { id: 266, de: "Wann schließt es?",           en: "When does it close?", tr: "Ne zaman kapanıyor?",         pron: "Ne sa-man ka-pa-nı-jor",      cat: "basics", sub: "Praktisch" },
  { id: 267, de: "Gibt es WiFi hier?",          en: "Is there WiFi here?", tr: "Burada WiFi var mı?",         pron: "Bu-ra-da waj-faj war mı",     cat: "basics", sub: "Praktisch" },
  { id: 268, de: "Wo ist die Toilette?",        en: "Where is the toilet?", tr: "Tuvalet nerede?",             pron: "Tu-wa-let ne-re-de",           cat: "basics", sub: "Praktisch" },
  { id: 269, de: "Einen Moment bitte.",         en: "One moment please.", tr: "Bir dakika lütfen.",          pron: "Bir da-ki-ka ljüt-fen",        cat: "basics", sub: "Praktisch" },
  { id: 270, de: "Sehr gerne! / Mit Freude!",  en: "Gladly! / With pleasure!", tr: "Memnuniyetle!",               pron: "Mem-nu-ni-jet-le",             cat: "basics", sub: "Praktisch" },
  { id: 271, de: "Schade! / Was ein Pech!",    en: "Too bad! / What bad luck!", tr: "Yazık! / Ne yazık ki!",       pron: "Ja-sık / Ne ja-sık ki",       cat: "basics", sub: "Praktisch" },
  { id: 272, de: "Gesundheit! (beim Niesen)",  en: "Bless you! (when sneezing)", tr: "Çok yaşa!",                   pron: "Tschok ja-scha",               cat: "basics", sub: "Praktisch" },
  { id: 273, de: "Glückwunsch!",               en: "Congratulations!", tr: "Tebrikler!",                  pron: "Teb-rik-ler",                  cat: "basics", sub: "Praktisch" },
  { id: 274, de: "Alles Gute!",                en: "All the best! / Good luck!", tr: "İyi şanslar! / Başarılar!",   pron: "İyi schan-slar / Ba-scha-rı-lar", cat: "basics", sub: "Praktisch" },
  { id: 275, de: "Zum Wohl! / Prost!",         en: "Cheers!", tr: "Şerefe!",                     pron: "Sche-re-fe",                   cat: "basics", sub: "Praktisch" },

  // ─── FARBEN (fürs Einkaufen) ─────────────────────────────────────────────
  { id: 280, de: "rot",                         en: "red", tr: "kırmızı",                     pron: "kır-mı-sı",                    cat: "urlaub", sub: "Farben" },
  { id: 281, de: "blau",                        en: "blue", tr: "mavi",                        pron: "ma-wi",                        cat: "urlaub", sub: "Farben" },
  { id: 282, de: "grün",                        en: "green", tr: "yeşil",                       pron: "je-schil",                     cat: "urlaub", sub: "Farben" },
  { id: 283, de: "gelb",                        en: "yellow", tr: "sarı",                        pron: "sa-rı",                        cat: "urlaub", sub: "Farben" },
  { id: 284, de: "weiß",                        en: "white", tr: "beyaz",                       pron: "be-jas",                       cat: "urlaub", sub: "Farben" },
  { id: 285, de: "schwarz",                     en: "black", tr: "siyah",                       pron: "si-jah",                       cat: "urlaub", sub: "Farben" },
  { id: 286, de: "braun",                       en: "brown", tr: "kahverengi",                  pron: "kah-we-ren-gi",                cat: "urlaub", sub: "Farben" },
  { id: 287, de: "orange",                      en: "orange", tr: "turuncu",                     pron: "tu-run-dschu",                 cat: "urlaub", sub: "Farben" },
  { id: 288, de: "rosa / pink",                 en: "pink", tr: "pembe",                       pron: "pem-be",                       cat: "urlaub", sub: "Farben" },
  { id: 289, de: "grau",                        en: "gray", tr: "gri",                         pron: "gri",                          cat: "urlaub", sub: "Farben" },
  { id: 290, de: "Haben Sie das in einer anderen Farbe?", en: "Do you have this in another color?", tr: "Başka rengi var mı?", pron: "Basch-ka ren-gi war mı",   cat: "urlaub", sub: "Farben" },
  { id: 291, de: "Haben Sie das in einer anderen Größe?", en: "Do you have this in another size?", tr: "Başka bedeni var mı?", pron: "Basch-ka be-de-ni war mı", cat: "urlaub", sub: "Farben" },
  { id: 292, de: "Das ist zu groß.",            en: "That's too big.", tr: "Bu çok büyük.",               pron: "Bu tschok bjü-jük",            cat: "urlaub", sub: "Farben" },
  { id: 293, de: "Das ist zu klein.",           en: "That's too small.", tr: "Bu çok küçük.",               pron: "Bu tschok kjü-tschük",         cat: "urlaub", sub: "Farben" },
  { id: 294, de: "Kann ich das anprobieren?",   en: "Can I try this on?", tr: "Deneyebilir miyim?",          pron: "De-ne-je-bi-lir mi-jim",      cat: "urlaub", sub: "Farben" },

  // ─── ESSEN & GETRÄNKE ERWEITERT ──────────────────────────────────────────
  { id: 300, de: "Das Frühstück",               en: "Breakfast", tr: "Kahvaltı",                    pron: "Kah-wal-tı",                   cat: "urlaub", sub: "Essen" },
  { id: 301, de: "Das Ei / Die Eier",           en: "The egg / The eggs", tr: "Yumurta",                     pron: "Ju-mur-ta",                    cat: "urlaub", sub: "Essen" },
  { id: 302, de: "Der Käse",                    en: "The cheese", tr: "Peynir",                      pron: "Pej-nir",                      cat: "urlaub", sub: "Essen" },
  { id: 303, de: "Der Joghurt",                 en: "The yogurt", tr: "Yoğurt",                      pron: "Jo-urt",                       cat: "urlaub", sub: "Essen" },
  { id: 304, de: "Der Honig",                   en: "The honey", tr: "Bal",                         pron: "bal",                          cat: "urlaub", sub: "Essen" },
  { id: 305, de: "Die Olive",                   en: "The olive", tr: "Zeytin",                      pron: "Sej-tin",                      cat: "urlaub", sub: "Essen" },
  { id: 306, de: "Die Tomate",                  en: "The tomato", tr: "Domates",                     pron: "Do-ma-tes",                    cat: "urlaub", sub: "Essen" },
  { id: 307, de: "Die Gurke",                   en: "The cucumber", tr: "Salatalık",                   pron: "Sa-la-ta-lık",                 cat: "urlaub", sub: "Essen" },
  { id: 308, de: "Die Suppe",                   en: "The soup", tr: "Çorba",                       pron: "Tschor-ba",                    cat: "urlaub", sub: "Essen" },
  { id: 309, de: "Der Salat",                   en: "The salad", tr: "Salata",                      pron: "Sa-la-ta",                     cat: "urlaub", sub: "Essen" },
  { id: 310, de: "Der Reis",                    en: "The rice", tr: "Pilav",                       pron: "Pi-law",                       cat: "urlaub", sub: "Essen" },
  { id: 311, de: "Das Hähnchen",                en: "The chicken", tr: "Tavuk",                       pron: "Ta-wuk",                       cat: "urlaub", sub: "Essen" },
  { id: 312, de: "Das Lamm",                    en: "The lamb", tr: "Kuzu",                        pron: "Ku-su",                        cat: "urlaub", sub: "Essen" },
  { id: 313, de: "Die Garnelen",                en: "The shrimp", tr: "Karides",                     pron: "Ka-ri-des",                    cat: "urlaub", sub: "Essen" },
  { id: 314, de: "Das Eis",                     en: "The ice cream", tr: "Dondurma",                    pron: "Don-dur-ma",                   cat: "urlaub", sub: "Essen" },
  { id: 315, de: "Das Bier",                    en: "The beer", tr: "Bira",                        pron: "Bi-ra",                        cat: "urlaub", sub: "Essen" },
  { id: 316, de: "Der Wein",                    en: "The wine", tr: "Şarap",                       pron: "Scha-rap",                     cat: "urlaub", sub: "Essen" },
  { id: 317, de: "Der Fruchtsaft",              en: "The fruit juice", tr: "Meyve suyu",                  pron: "Mej-we su-ju",                 cat: "urlaub", sub: "Essen" },
  { id: 318, de: "Ayran (Joghurtgetränk)",      en: "Ayran (yogurt drink)", tr: "Ayran",                       pron: "Aj-ran",                       cat: "urlaub", sub: "Essen" },
  { id: 319, de: "Scharf / würzig",             en: "Spicy", tr: "Acı / Baharatlı",             pron: "A-dshı / Ba-ha-rat-lı",        cat: "urlaub", sub: "Essen" },
  { id: 320, de: "Nicht scharf bitte.",         en: "Not spicy please.", tr: "Acısız lütfen.",              pron: "A-dshı-sıs ljüt-fen",          cat: "urlaub", sub: "Essen" },
  { id: 321, de: "Ohne ... bitte.",             en: "Without ... please.", tr: "... siz lütfen.",             pron: "sıs ljüt-fen",                 cat: "urlaub", sub: "Essen" },
  { id: 322, de: "Leitungswasser",              en: "Tap water", tr: "Musluk suyu",                 pron: "Mus-luk su-ju",                cat: "urlaub", sub: "Essen" },
  { id: 323, de: "Ein Glas / Eine Flasche",     en: "A glass / A bottle", tr: "Bir bardak / Bir şişe",       pron: "Bir bar-dak / Bir schi-sche",  cat: "urlaub", sub: "Essen" },

  // ─── WETTER ──────────────────────────────────────────────────────────────
  { id: 330, de: "Wie ist das Wetter?",         en: "What's the weather like?", tr: "Hava nasıl?",                 pron: "Ha-wa na-sıl",                 cat: "basics", sub: "Wetter" },
  { id: 331, de: "Es ist kalt.",                en: "It's cold.", tr: "Hava soğuk.",                 pron: "Ha-wa so-uk",                  cat: "basics", sub: "Wetter" },
  { id: 332, de: "Es ist warm.",                en: "It's warm.", tr: "Hava sıcak.",                 pron: "Ha-wa sı-dschak",              cat: "basics", sub: "Wetter" },
  { id: 333, de: "Es regnet.",                  en: "It's raining.", tr: "Yağmur yağıyor.",             pron: "Ja-mur ja-ı-jor",             cat: "basics", sub: "Wetter" },
  { id: 334, de: "Die Sonne scheint.",          en: "The sun is shining.", tr: "Güneş parlıyor.",             pron: "Gjü-nesch par-lı-jor",         cat: "basics", sub: "Wetter" },
  { id: 335, de: "Es ist windig.",              en: "It's windy.", tr: "Rüzgar var.",                 pron: "Rüs-gar war",                  cat: "basics", sub: "Wetter" },
  { id: 336, de: "Wird es morgen schön?",       en: "Will it be nice tomorrow?", tr: "Yarın hava güzel olacak mı?", pron: "Ja-rın ha-wa gjü-sel o-la-dshak mı", cat: "basics", sub: "Wetter" },
  { id: 337, de: "Das Gewitter",                en: "The thunderstorm", tr: "Fırtına",                     pron: "Fır-tı-na",                    cat: "basics", sub: "Wetter" },
  { id: 338, de: "Der Schatten",                en: "The shade", tr: "Gölge",                       pron: "Göl-ge",                       cat: "basics", sub: "Wetter" },

  // ─── VERBEN (Grundformen) ────────────────────────────────────────────────
  { id: 400, de: "sein",                        en: "to be", tr: "olmak",                       pron: "ol-mak",                        cat: "basics", sub: "Verben" },
  { id: 401, de: "haben",                       en: "to have", tr: "sahip olmak",                 pron: "sa-hip ol-mak",                 cat: "basics", sub: "Verben" },
  { id: 402, de: "machen / tun",                en: "to do / to make", tr: "yapmak",                      pron: "jap-mak",                       cat: "basics", sub: "Verben" },
  { id: 403, de: "gehen",                       en: "to go", tr: "gitmek",                      pron: "git-mek",                       cat: "basics", sub: "Verben" },
  { id: 404, de: "kommen",                      en: "to come", tr: "gelmek",                      pron: "gel-mek",                       cat: "basics", sub: "Verben" },
  { id: 405, de: "wollen / möchten",            en: "to want", tr: "istemek",                     pron: "is-te-mek",                     cat: "basics", sub: "Verben" },
  { id: 406, de: "können",                      en: "to be able to", tr: "yapabilmek",                  pron: "ja-pa-bil-mek",                 cat: "basics", sub: "Verben" },
  { id: 407, de: "wissen",                      en: "to know", tr: "bilmek",                      pron: "bil-mek",                       cat: "basics", sub: "Verben" },
  { id: 408, de: "sehen",                       en: "to see", tr: "görmek",                      pron: "gör-mek",                       cat: "basics", sub: "Verben" },
  { id: 409, de: "geben",                       en: "to give", tr: "vermek",                      pron: "wer-mek",                       cat: "basics", sub: "Verben" },
  { id: 410, de: "nehmen",                      en: "to take", tr: "almak",                       pron: "al-mak",                        cat: "basics", sub: "Verben" },
  { id: 411, de: "sagen",                       en: "to say", tr: "söylemek",                    pron: "sjöj-le-mek",                   cat: "basics", sub: "Verben" },
  { id: 412, de: "finden",                      en: "to find", tr: "bulmak",                      pron: "bul-mak",                       cat: "basics", sub: "Verben" },
  { id: 413, de: "brauchen",                    en: "to need", tr: "ihtiyacı olmak",              pron: "ih-ti-ja-dschı ol-mak",         cat: "basics", sub: "Verben" },
  { id: 414, de: "kaufen",                      en: "to buy", tr: "satın almak",                 pron: "sa-tın al-mak",                 cat: "basics", sub: "Verben" },
  { id: 415, de: "bezahlen",                    en: "to pay", tr: "ödemek",                      pron: "ö-de-mek",                      cat: "basics", sub: "Verben" },
  { id: 416, de: "essen",                       en: "to eat", tr: "yemek",                       pron: "je-mek",                        cat: "basics", sub: "Verben" },
  { id: 417, de: "trinken",                     en: "to drink", tr: "içmek",                       pron: "itsch-mek",                     cat: "basics", sub: "Verben" },
  { id: 418, de: "schlafen",                    en: "to sleep", tr: "uyumak",                      pron: "u-ju-mak",                      cat: "basics", sub: "Verben" },
  { id: 419, de: "warten",                      en: "to wait", tr: "beklemek",                    pron: "bek-le-mek",                    cat: "basics", sub: "Verben" },
  { id: 420, de: "helfen",                      en: "to help", tr: "yardım etmek",                pron: "jar-dım et-mek",                cat: "basics", sub: "Verben" },
  { id: 421, de: "verstehen",                   en: "to understand", tr: "anlamak",                     pron: "an-la-mak",                     cat: "basics", sub: "Verben" },
  { id: 422, de: "sprechen",                    en: "to speak", tr: "konuşmak",                    pron: "ko-nusch-mak",                  cat: "basics", sub: "Verben" },
  { id: 423, de: "fragen",                      en: "to ask", tr: "sormak",                      pron: "sor-mak",                       cat: "basics", sub: "Verben" },
  { id: 424, de: "arbeiten",                    en: "to work", tr: "çalışmak",                    pron: "tscha-lısch-mak",               cat: "basics", sub: "Verben" },
  { id: 425, de: "fahren / gefahren werden",    en: "to drive / to ride", tr: "sürmek",                      pron: "sjür-mek",                      cat: "basics", sub: "Verben" },
  { id: 426, de: "ankommen",                    en: "to arrive", tr: "varmak",                      pron: "war-mak",                       cat: "basics", sub: "Verben" },
  { id: 427, de: "beginnen / anfangen",         en: "to begin / to start", tr: "başlamak",                    pron: "basch-la-mak",                  cat: "basics", sub: "Verben" },
  { id: 428, de: "aufhören / beenden",          en: "to stop / to finish", tr: "bitirmek",                    pron: "bi-tir-mek",                    cat: "basics", sub: "Verben" },
  { id: 429, de: "lieben / mögen",              en: "to love / to like", tr: "sevmek",                      pron: "sew-mek",                       cat: "basics", sub: "Verben" },

  // ─── ADJEKTIVE ───────────────────────────────────────────────────────────
  { id: 440, de: "groß",                        en: "big", tr: "büyük",                       pron: "bjü-jük",                       cat: "basics", sub: "Adjektive" },
  { id: 441, de: "klein",                       en: "small", tr: "küçük",                       pron: "kjü-tschük",                    cat: "basics", sub: "Adjektive" },
  { id: 442, de: "gut",                         en: "good", tr: "iyi",                         pron: "i-ji",                          cat: "basics", sub: "Adjektive" },
  { id: 443, de: "schlecht",                    en: "bad", tr: "kötü",                        pron: "kö-tü",                         cat: "basics", sub: "Adjektive" },
  { id: 444, de: "neu",                         en: "new", tr: "yeni",                        pron: "je-ni",                         cat: "basics", sub: "Adjektive" },
  { id: 445, de: "alt",                         en: "old", tr: "eski",                        pron: "es-ki",                         cat: "basics", sub: "Adjektive" },
  { id: 446, de: "schön",                       en: "beautiful", tr: "güzel",                       pron: "gjü-sel",                       cat: "basics", sub: "Adjektive" },
  { id: 447, de: "hässlich",                    en: "ugly", tr: "çirkin",                      pron: "tschir-kin",                    cat: "basics", sub: "Adjektive" },
  { id: 448, de: "schnell",                     en: "fast", tr: "hızlı",                       pron: "hıs-lı",                        cat: "basics", sub: "Adjektive" },
  { id: 449, de: "langsam",                     en: "slow", tr: "yavaş",                       pron: "ja-wasch",                      cat: "basics", sub: "Adjektive" },
  { id: 450, de: "billig / günstig",            en: "cheap", tr: "ucuz",                        pron: "u-dschus",                      cat: "basics", sub: "Adjektive" },
  { id: 451, de: "teuer",                       en: "expensive", tr: "pahalı",                      pron: "pa-ha-lı",                      cat: "basics", sub: "Adjektive" },
  { id: 452, de: "sauber",                      en: "clean", tr: "temiz",                       pron: "te-mis",                        cat: "basics", sub: "Adjektive" },
  { id: 453, de: "schmutzig",                   en: "dirty", tr: "kirli",                       pron: "kir-li",                        cat: "basics", sub: "Adjektive" },
  { id: 454, de: "leicht / einfach",            en: "easy", tr: "kolay",                       pron: "ko-laj",                        cat: "basics", sub: "Adjektive" },
  { id: 455, de: "schwierig",                   en: "difficult", tr: "zor",                         pron: "sor",                           cat: "basics", sub: "Adjektive" },
  { id: 456, de: "voll",                        en: "full", tr: "dolu",                        pron: "do-lu",                         cat: "basics", sub: "Adjektive" },
  { id: 457, de: "leer",                        en: "empty", tr: "boş",                         pron: "bosch",                         cat: "basics", sub: "Adjektive" },
  { id: 458, de: "nah",                         en: "near", tr: "yakın",                       pron: "ja-kın",                        cat: "basics", sub: "Adjektive" },
  { id: 459, de: "weit / entfernt",             en: "far", tr: "uzak",                        pron: "u-sak",                         cat: "basics", sub: "Adjektive" },
  { id: 460, de: "früh",                        en: "early", tr: "erken",                       pron: "er-ken",                        cat: "basics", sub: "Adjektive" },
  { id: 461, de: "spät",                        en: "late", tr: "geç",                         pron: "getsch",                        cat: "basics", sub: "Adjektive" },
  { id: 462, de: "müde",                        en: "tired", tr: "yorgun",                      pron: "jor-gun",                       cat: "basics", sub: "Adjektive" },
  { id: 463, de: "glücklich",                   en: "happy", tr: "mutlu",                       pron: "mut-lu",                        cat: "basics", sub: "Adjektive" },
  { id: 464, de: "traurig",                     en: "sad", tr: "üzgün",                       pron: "üs-gjün",                       cat: "basics", sub: "Adjektive" },
  { id: 465, de: "wichtig",                     en: "important", tr: "önemli",                      pron: "ö-nem-li",                      cat: "basics", sub: "Adjektive" },

  // ─── FAMILIE ERWEITERT ───────────────────────────────────────────────────
  { id: 480, de: "Tante",                       en: "Aunt", tr: "Teyze / Hala",                pron: "Tej-se / Ha-la",                cat: "alltag", sub: "Familie" },
  { id: 481, de: "Onkel",                       en: "Uncle", tr: "Dayı / Amca",                 pron: "Da-jı / Am-dscha",              cat: "alltag", sub: "Familie" },
  { id: 482, de: "Cousin / Cousine",            en: "Cousin", tr: "Kuzen",                       pron: "Ku-sen",                        cat: "alltag", sub: "Familie" },
  { id: 483, de: "Schwiegermutter",             en: "Mother-in-law", tr: "Kayınvalide",                 pron: "Ka-jın-wa-li-de",               cat: "alltag", sub: "Familie" },
  { id: 484, de: "Schwiegervater",              en: "Father-in-law", tr: "Kayınpeder",                  pron: "Ka-jın-pe-der",                 cat: "alltag", sub: "Familie" },
  { id: 485, de: "Schwager",                    en: "Brother-in-law", tr: "Enişte / Kayınbirader",       pron: "E-nisch-te / Ka-jın-bi-ra-der", cat: "alltag", sub: "Familie" },
  { id: 486, de: "Schwägerin",                  en: "Sister-in-law", tr: "Görümce / Yenge",             pron: "Gö-rüm-dsche / Jen-ge",         cat: "alltag", sub: "Familie" },
  { id: 487, de: "Enkelkind",                   en: "Grandchild", tr: "Torun",                       pron: "To-run",                       cat: "alltag", sub: "Familie" },
  { id: 488, de: "Baby",                        en: "Baby", tr: "Bebek",                       pron: "Be-bek",                        cat: "alltag", sub: "Familie" },
  { id: 489, de: "Verlobte/r",                  en: "Fiancé(e)", tr: "Nişanlı",                     pron: "Ni-schan-lı",                   cat: "alltag", sub: "Familie" },
  { id: 490, de: "Freund/in (Beziehung)",       en: "Girlfriend/Boyfriend", tr: "Sevgili",                     pron: "Sew-gi-li",                     cat: "alltag", sub: "Familie" },
  { id: 491, de: "Freund/in (platonisch)",      en: "Friend", tr: "Arkadaş",                     pron: "Ar-ka-dasch",                   cat: "alltag", sub: "Familie" },

  // ─── WEGBESCHREIBUNG ─────────────────────────────────────────────────────
  { id: 500, de: "Wie komme ich zu ...?",       en: "How do I get to ...?", tr: "... nasıl gidebilirim?",      pron: "... na-sıl gi-de-bi-li-rim",   cat: "urlaub", sub: "Wegbeschreibung" },
  { id: 501, de: "Ist das in der Nähe?",        en: "Is that nearby?", tr: "Bu yakında mı?",              pron: "Bu ja-kın-da mı",               cat: "urlaub", sub: "Wegbeschreibung" },
  { id: 502, de: "Zu Fuß oder mit dem Auto?",   en: "On foot or by car?", tr: "Yürüyerek mi, arabayla mı?",  pron: "Jü-rü-je-rek mi, a-ra-baj-la mı", cat: "urlaub", sub: "Wegbeschreibung" },
  { id: 503, de: "An der Ampel links.",         en: "Left at the traffic light.", tr: "Trafik ışığında sola.",       pron: "Tra-fik ı-schı-ın-da so-la",   cat: "urlaub", sub: "Wegbeschreibung" },
  { id: 504, de: "An der Ecke rechts.",         en: "Right at the corner.", tr: "Köşeden sağa.",               pron: "Kö-sche-den saa",              cat: "urlaub", sub: "Wegbeschreibung" },
  { id: 505, de: "Gegenüber von ...",           en: "Across from ...", tr: "... karşısında",              pron: "kar-schı-sın-da",              cat: "urlaub", sub: "Wegbeschreibung" },
  { id: 506, de: "Neben ...",                   en: "Next to ...", tr: "... yanında",                 pron: "ja-nın-da",                    cat: "urlaub", sub: "Wegbeschreibung" },
  { id: 507, de: "Zwischen ... und ...",        en: "Between ... and ...", tr: "... ile ... arasında",        pron: "i-le ... a-ra-sın-da",         cat: "urlaub", sub: "Wegbeschreibung" },
  { id: 508, de: "Die erste Straße rechts.",    en: "The first street on the right.", tr: "İlk sokak sağda.",            pron: "İlk so-kak saa-da",            cat: "urlaub", sub: "Wegbeschreibung" },
  { id: 509, de: "Ich habe mich verlaufen.",    en: "I got lost.", tr: "Kayboldum.",                  pron: "Kaj-bol-dum",                  cat: "urlaub", sub: "Wegbeschreibung" },
  { id: 510, de: "Können Sie mir helfen?",      en: "Can you help me?", tr: "Bana yardım edebilir misiniz?", pron: "Ba-na jar-dım e-de-bi-lir mi-si-nis", cat: "urlaub", sub: "Wegbeschreibung" },
  { id: 511, de: "Die Karte / Der Stadtplan",   en: "The map", tr: "Harita",                      pron: "Ha-ri-ta",                     cat: "urlaub", sub: "Wegbeschreibung" },

  // ─── VERKEHRSMITTEL ──────────────────────────────────────────────────────
  { id: 520, de: "Der Bus",                     en: "The bus", tr: "Otobüs",                      pron: "O-to-bjüs",                    cat: "urlaub", sub: "Verkehrsmittel" },
  { id: 521, de: "Die Fähre",                   en: "The ferry", tr: "Vapur / Feribot",             pron: "Wa-pur / Fe-ri-bot",           cat: "urlaub", sub: "Verkehrsmittel" },
  { id: 522, de: "Die U-Bahn",                  en: "The subway", tr: "Metro",                       pron: "Met-ro",                       cat: "urlaub", sub: "Verkehrsmittel" },
  { id: 523, de: "Die Straßenbahn",             en: "The tram", tr: "Tramvay",                     pron: "Tram-waj",                     cat: "urlaub", sub: "Verkehrsmittel" },
  { id: 524, de: "Der Minibus (Sammeltaxi)",    en: "The minibus (shared taxi)", tr: "Dolmuş",                      pron: "Dol-musch",                    cat: "urlaub", sub: "Verkehrsmittel" },
  { id: 525, de: "Der Mietwagen",               en: "The rental car", tr: "Kiralık araba",               pron: "Ki-ra-lık a-ra-ba",            cat: "urlaub", sub: "Verkehrsmittel" },
  { id: 526, de: "Die Bushaltestelle",          en: "The bus stop", tr: "Otobüs durağı",               pron: "O-to-bjüs du-raa",             cat: "urlaub", sub: "Verkehrsmittel" },
  { id: 527, de: "Einfache Fahrt",              en: "One-way trip", tr: "Tek yön",                     pron: "Tek jön",                      cat: "urlaub", sub: "Verkehrsmittel" },
  { id: 528, de: "Hin- und Rückfahrt",          en: "Round trip", tr: "Gidiş dönüş",                 pron: "Gi-dish dö-njüsch",            cat: "urlaub", sub: "Verkehrsmittel" },
  { id: 529, de: "Wo muss ich umsteigen?",      en: "Where do I have to change?", tr: "Nerede aktarma yapmalıyım?",  pron: "Ne-re-de ak-tar-ma jap-ma-lı-jım", cat: "urlaub", sub: "Verkehrsmittel" },
  { id: 530, de: "Ist dieser Platz frei?",      en: "Is this seat free?", tr: "Bu koltuk boş mu?",           pron: "Bu kol-tuk bosch mu",          cat: "urlaub", sub: "Verkehrsmittel" },
  { id: 531, de: "Der Koffer / Das Gepäck",     en: "The suitcase / The luggage", tr: "Bavul / Bagaj",               pron: "Ba-wul / Ba-gash",             cat: "urlaub", sub: "Verkehrsmittel" },

  // ─── ZEIT DETAIL ─────────────────────────────────────────────────────────
  { id: 540, de: "Um wie viel Uhr?",            en: "At what time?", tr: "Saat kaçta?",                 pron: "Sa-at katsch-ta",              cat: "basics", sub: "Zeit" },
  { id: 541, de: "Es ist drei Uhr.",            en: "It's three o'clock.", tr: "Saat üç.",                    pron: "Sa-at ütsch",                  cat: "basics", sub: "Zeit" },
  { id: 542, de: "Halb vier.",                  en: "Half past three.", tr: "Üç buçuk.",                   pron: "Ütsch bu-tschuk",              cat: "basics", sub: "Zeit" },
  { id: 543, de: "Viertel nach zwei.",          en: "Quarter past two.", tr: "İkiyi çeyrek geçiyor.",       pron: "İ-ki-ji tschej-rek ge-tschi-jor", cat: "basics", sub: "Zeit" },
  { id: 544, de: "diese Woche",                 en: "this week", tr: "bu hafta",                    pron: "bu haf-ta",                    cat: "basics", sub: "Zeit" },
  { id: 545, de: "nächste Woche",               en: "next week", tr: "gelecek hafta",               pron: "ge-le-dschek haf-ta",          cat: "basics", sub: "Zeit" },
  { id: 546, de: "letzte Woche",                en: "last week", tr: "geçen hafta",                 pron: "ge-tschen haf-ta",             cat: "basics", sub: "Zeit" },
  { id: 547, de: "dieser Monat",                en: "this month", tr: "bu ay",                       pron: "bu aj",                        cat: "basics", sub: "Zeit" },
  { id: 548, de: "morgens",                     en: "in the morning", tr: "sabahleyin",                  pron: "sa-bah-le-jin",                cat: "basics", sub: "Zeit" },
  { id: 549, de: "abends",                      en: "in the evening", tr: "akşamları",                   pron: "ak-scham-la-rı",               cat: "basics", sub: "Zeit" },
  { id: 550, de: "immer",                       en: "always", tr: "her zaman",                   pron: "her sa-man",                   cat: "basics", sub: "Zeit" },
  { id: 551, de: "nie",                         en: "never", tr: "asla / hiçbir zaman",         pron: "as-la / hitsch-bir sa-man",    cat: "basics", sub: "Zeit" },
  { id: 552, de: "manchmal",                    en: "sometimes", tr: "bazen",                       pron: "ba-sen",                       cat: "basics", sub: "Zeit" },
  { id: 553, de: "jetzt",                       en: "now", tr: "şimdi",                       pron: "schim-di",                     cat: "basics", sub: "Zeit" },
  { id: 554, de: "später",                      en: "later", tr: "sonra",                       pron: "son-ra",                       cat: "basics", sub: "Zeit" },

  // ─── UNTERKUNFT & CAMPING ────────────────────────────────────────────────
  { id: 560, de: "Die Klimaanlage",             en: "The air conditioning", tr: "Klima",                       pron: "Kli-ma",                       cat: "urlaub", sub: "Unterkunft" },
  { id: 561, de: "Die Heizung",                 en: "The heating", tr: "Kalorifer",                   pron: "Ka-lo-ri-fer",                 cat: "urlaub", sub: "Unterkunft" },
  { id: 562, de: "Der Balkon",                  en: "The balcony", tr: "Balkon",                      pron: "Bal-kon",                      cat: "urlaub", sub: "Unterkunft" },
  { id: 563, de: "Die Aussicht / Der Meerblick",en: "The view / The sea view", tr: "Manzara / Deniz manzarası",   pron: "Man-sa-ra / De-nis man-sa-ra-sı", cat: "urlaub", sub: "Unterkunft" },
  { id: 564, de: "Funktioniert nicht.",         en: "Doesn't work.", tr: "Çalışmıyor.",                 pron: "Tscha-lısch-mı-jor",           cat: "urlaub", sub: "Unterkunft" },
  { id: 565, de: "Es gibt kein warmes Wasser.", en: "There's no hot water.", tr: "Sıcak su yok.",               pron: "Sı-dschak su jok",             cat: "urlaub", sub: "Unterkunft" },
  { id: 566, de: "Können Sie mich um 7 Uhr wecken?", en: "Can you wake me at 7 o'clock?", tr: "Beni yedide uyandırabilir misiniz?", pron: "Be-ni je-di-de u-jan-dı-ra-bi-lir mi-si-nis", cat: "urlaub", sub: "Unterkunft" },
  { id: 567, de: "Das Zimmer ist zu laut.",     en: "The room is too loud.", tr: "Oda çok gürültülü.",          pron: "O-da tschok gjü-rül-tü-lü",    cat: "urlaub", sub: "Unterkunft" },
  { id: 568, de: "Können wir das Zimmer wechseln?", en: "Can we change rooms?", tr: "Odayı değiştirebilir miyiz?", pron: "O-da-jı de-isch-ti-re-bi-lir mi-jis", cat: "urlaub", sub: "Unterkunft" },
  { id: 569, de: "Wo kann ich Wäsche waschen?", en: "Where can I do laundry?", tr: "Nerede çamaşır yıkayabilirim?", pron: "Ne-re-de tscha-ma-schır jı-ka-ja-bi-li-rim", cat: "urlaub", sub: "Unterkunft" },
  { id: 570, de: "Der Safe / Tresor",           en: "The safe", tr: "Kasa",                        pron: "Ka-sa",                        cat: "urlaub", sub: "Unterkunft" },
  { id: 571, de: "Die Bettwäsche",              en: "The bed linen", tr: "Nevresim",                    pron: "Ne-wre-sim",                   cat: "urlaub", sub: "Unterkunft" },

  // ─── KAFFEE & CAFÉ ───────────────────────────────────────────────────────
  { id: 600, de: "Türkischer Kaffee",           en: "Turkish coffee", tr: "Türk kahvesi",                pron: "Türk kah-we-si",               cat: "urlaub", sub: "Kaffee" },
  { id: 601, de: "Ungesüßt",                    en: "Unsweetened", tr: "Sade",                        pron: "Sa-de",                        cat: "urlaub", sub: "Kaffee" },
  { id: 602, de: "Leicht gesüßt",               en: "Slightly sweetened", tr: "Az şekerli",                  pron: "As sche-ker-li",               cat: "urlaub", sub: "Kaffee" },
  { id: 603, de: "Mittel gesüßt",               en: "Medium sweetened", tr: "Orta şekerli",                pron: "Or-ta sche-ker-li",            cat: "urlaub", sub: "Kaffee" },
  { id: 604, de: "Süß",                         en: "Sweet", tr: "Şekerli",                     pron: "Sche-ker-li",                  cat: "urlaub", sub: "Kaffee" },
  { id: 605, de: "Nescafé / Löslicher Kaffee",  en: "Instant coffee", tr: "Neskafe",                     pron: "Nes-ka-fe",                    cat: "urlaub", sub: "Kaffee" },
  { id: 606, de: "Filterkaffee",                en: "Filter coffee", tr: "Filtre kahve",                pron: "Fil-tre kah-we",               cat: "urlaub", sub: "Kaffee" },
  { id: 607, de: "Milchkaffee",                 en: "Coffee with milk", tr: "Sütlü kahve",                 pron: "Süt-lü kah-we",                cat: "urlaub", sub: "Kaffee" },
  { id: 608, de: "Espresso",                    en: "Espresso", tr: "Espresso",                    pron: "Es-pres-so",                   cat: "urlaub", sub: "Kaffee" },
  { id: 609, de: "Cappuccino",                  en: "Cappuccino", tr: "Kapuçino",                    pron: "Ka-pu-tschi-no",               cat: "urlaub", sub: "Kaffee" },
  { id: 610, de: "Latte macchiato",             en: "Latte macchiato", tr: "Sütlü latte",                 pron: "Süt-lü lat-te",                cat: "urlaub", sub: "Kaffee" },
  { id: 611, de: "Heiß / Kalt",                 en: "Hot / Cold", tr: "Sıcak / Soğuk",               pron: "Sı-dschak / So-uk",            cat: "urlaub", sub: "Kaffee" },
  { id: 612, de: "Eiskaffee",                   en: "Iced coffee", tr: "Soğuk kahve",                 pron: "So-uk kah-we",                 cat: "urlaub", sub: "Kaffee" },
  { id: 613, de: "Schwarzer Tee",               en: "Black tea", tr: "Siyah çay",                   pron: "Si-jah tschaj",                cat: "urlaub", sub: "Kaffee" },
  { id: 614, de: "Apfeltee",                    en: "Apple tea", tr: "Elma çayı",                   pron: "El-ma tscha-jı",               cat: "urlaub", sub: "Kaffee" },
  { id: 615, de: "Kräutertee",                  en: "Herbal tea", tr: "Bitki çayı",                  pron: "Bit-ki tscha-jı",              cat: "urlaub", sub: "Kaffee" },
  { id: 616, de: "Ein Glas Tee",                en: "A glass of tea", tr: "Bir bardak çay",              pron: "Bir bar-dak tschaj",           cat: "urlaub", sub: "Kaffee" },
  { id: 617, de: "Zucker",                      en: "Sugar", tr: "Şeker",                       pron: "Sche-ker",                     cat: "urlaub", sub: "Kaffee" },
  { id: 618, de: "Milch",                       en: "Milk", tr: "Süt",                         pron: "süt",                          cat: "urlaub", sub: "Kaffee" },
  { id: 619, de: "Können wir hier drinnen sitzen?", en: "Can we sit inside?", tr: "İçeride oturabilir miyiz?", pron: "İ-tsche-ri-de o-tu-ra-bi-lir mi-jis", cat: "urlaub", sub: "Kaffee" },
  { id: 620, de: "Können wir draußen sitzen?",  en: "Can we sit outside?", tr: "Dışarıda oturabilir miyiz?",  pron: "Dı-scha-rı-da o-tu-ra-bi-lir mi-jis", cat: "urlaub", sub: "Kaffee" },
  { id: 621, de: "Zum Mitnehmen, bitte.",       en: "To go, please.", tr: "Paket olsun, lütfen.",        pron: "Pa-ket ol-sun, ljüt-fen",      cat: "urlaub", sub: "Kaffee" },
  { id: 622, de: "Zum Hieressen.",              en: "For here.", tr: "Burada içeceğim.",            pron: "Bu-ra-da i-tsche-dsche-im",    cat: "urlaub", sub: "Kaffee" },
  { id: 623, de: "Ich möchte einen Kaffee, bitte.", en: "I would like a coffee, please.", tr: "Bir kahve istiyorum, lütfen.", pron: "Bir kah-we is-ti-jo-rum, ljüt-fen", cat: "urlaub", sub: "Kaffee" },
  { id: 624, de: "Noch einen, bitte.",          en: "One more, please.", tr: "Bir tane daha, lütfen.",      pron: "Bir ta-ne da-ha, ljüt-fen",    cat: "urlaub", sub: "Kaffee" },
  { id: 625, de: "Der Kuchen",                  en: "The cake", tr: "Kek / Pasta",                 pron: "Kek / Pas-ta",                 cat: "urlaub", sub: "Kaffee" },
  { id: 626, de: "Baklava",                     en: "Baklava", tr: "Baklava",                     pron: "Bak-la-wa",                    cat: "urlaub", sub: "Kaffee" },
  { id: 627, de: "Türkische Freude / Lokum",    en: "Turkish delight", tr: "Lokum",                       pron: "Lo-kum",                       cat: "urlaub", sub: "Kaffee" },
  { id: 628, de: "Kann ich mein Glück lesen lassen?", en: "Can I have my fortune read?", tr: "Falıma bakılır mı?",    pron: "Fa-lı-ma ba-kı-lır mı",        cat: "urlaub", sub: "Kaffee" },

  // ─── RESTAURANT BESTELLEN ────────────────────────────────────────────────
  { id: 640, de: "Haben Sie einen freien Tisch?", en: "Do you have a free table?", tr: "Boş masanız var mı?",       pron: "Bosch ma-sa-nıs war mı",       cat: "urlaub", sub: "Bestellen" },
  { id: 641, de: "Wir sind zu viert.",           en: "There are four of us.", tr: "Dört kişiyiz.",              pron: "Dört ki-schi-jis",              cat: "urlaub", sub: "Bestellen" },
  { id: 642, de: "Draußen, bitte.",              en: "Outside, please.", tr: "Dışarıda, lütfen.",          pron: "Dı-scha-rı-da, ljüt-fen",      cat: "urlaub", sub: "Bestellen" },
  { id: 643, de: "Können wir bestellen?",        en: "Can we order?", tr: "Sipariş verebilir miyiz?",   pron: "Si-pa-risch we-re-bi-lir mi-jis", cat: "urlaub", sub: "Bestellen" },
  { id: 644, de: "Ich hätte gerne ...",          en: "I would like ...", tr: "... rica ediyorum.",         pron: "ri-dscha e-di-jo-rum",         cat: "urlaub", sub: "Bestellen" },
  { id: 645, de: "Ich nehme dasselbe.",          en: "I'll have the same.", tr: "Ben de aynısından.",         pron: "Ben de aj-nı-sın-dan",         cat: "urlaub", sub: "Bestellen" },
  { id: 646, de: "Was ist die Spezialität des Hauses?", en: "What's the house specialty?", tr: "Şefin önerisi nedir?", pron: "Sche-fin ö-ne-ri-si ne-dir",  cat: "urlaub", sub: "Bestellen" },
  { id: 647, de: "Als Vorspeise ...",            en: "As a starter ...", tr: "Başlangıç olarak ...",       pron: "Basch-lan-gıtsch o-la-rak",    cat: "urlaub", sub: "Bestellen" },
  { id: 648, de: "Als Hauptgericht ...",         en: "As a main course ...", tr: "Ana yemek olarak ...",       pron: "A-na je-mek o-la-rak",         cat: "urlaub", sub: "Bestellen" },
  { id: 649, de: "Als Nachspeise ...",           en: "As a dessert ...", tr: "Tatlı olarak ...",           pron: "Tat-lı o-la-rak",              cat: "urlaub", sub: "Bestellen" },
  { id: 650, de: "Wie wird das zubereitet?",     en: "How is this prepared?", tr: "Bu nasıl pişiriliyor?",      pron: "Bu na-sıl pi-schi-ri-li-jor", cat: "urlaub", sub: "Bestellen" },
  { id: 651, de: "Ist das scharf?",              en: "Is this spicy?", tr: "Bu acı mı?",                 pron: "Bu a-dschı mı",                cat: "urlaub", sub: "Bestellen" },
  { id: 652, de: "Enthält das Nüsse?",           en: "Does this contain nuts?", tr: "İçinde fındık var mı?",      pron: "İ-tschin-de fın-dık war mı",  cat: "urlaub", sub: "Bestellen" },
  { id: 653, de: "Ich habe eine Allergie.",      en: "I have an allergy.", tr: "Alerjim var.",               pron: "A-ler-dschim war",             cat: "urlaub", sub: "Bestellen" },
  { id: 654, de: "Ich bin Veganer.",             en: "I'm vegan.", tr: "Ben veganım.",               pron: "Ben we-ga-nım",                cat: "urlaub", sub: "Bestellen" },
  { id: 655, de: "Können wir noch etwas Brot haben?", en: "Can we have some more bread?", tr: "Biraz daha ekmek alabilir miyiz?", pron: "Bi-ras da-ha ek-mek a-la-bi-lir mi-jis", cat: "urlaub", sub: "Bestellen" },
  { id: 656, de: "Das habe ich nicht bestellt.", en: "I didn't order this.", tr: "Bunu ben sipariş etmedim.",  pron: "Bu-nu ben si-pa-risch et-me-dim", cat: "urlaub", sub: "Bestellen" },
  { id: 657, de: "Es fehlt noch etwas.",         en: "Something is missing.", tr: "Bir şey eksik.",             pron: "Bir schej ek-sik",              cat: "urlaub", sub: "Bestellen" },
  { id: 658, de: "Kann ich das zurückgeben?",    en: "Can I return this?", tr: "Bunu geri verebilir miyim?", pron: "Bu-nu ge-ri we-re-bi-lir mi-jim", cat: "urlaub", sub: "Bestellen" },
  { id: 659, de: "Es war kalt.",                 en: "It was cold.", tr: "Soğuktu.",                   pron: "So-uk-tu",                     cat: "urlaub", sub: "Bestellen" },
  { id: 660, de: "Kann ich das aufwärmen lassen?", en: "Can I get this reheated?", tr: "Bunu ısıtabilir misiniz?", pron: "Bu-nu ı-sı-ta-bi-lir mi-si-nis", cat: "urlaub", sub: "Bestellen" },
  { id: 661, de: "Können wir die Speisekarte nochmal sehen?", en: "Can we see the menu again?", tr: "Menüyü tekrar görebilir miyiz?", pron: "Me-nü-jü tek-rar gö-re-bi-lir mi-jis", cat: "urlaub", sub: "Bestellen" },
  { id: 662, de: "Ist der Service inklusive?",   en: "Is service included?", tr: "Servis dahil mi?",           pron: "Ser-wis da-hil mi",             cat: "urlaub", sub: "Bestellen" },
  { id: 663, de: "Trinkgeld",                    en: "Tip", tr: "Bahşiş",                     pron: "Bah-schisch",                  cat: "urlaub", sub: "Bestellen" },
  { id: 664, de: "Können wir zusammen zahlen?",  en: "Can we pay together?", tr: "Hesabı birlikte alabilir miyiz?", pron: "He-sa-bı bir-lik-te a-la-bi-lir mi-jis", cat: "urlaub", sub: "Bestellen" },
  { id: 665, de: "Das war ausgezeichnet!",       en: "That was excellent!", tr: "Harikaydı!",                 pron: "Ha-ri-kaj-dı",                 cat: "urlaub", sub: "Bestellen" },
  { id: 666, de: "Wir kommen wieder.",           en: "We'll come again.", tr: "Tekrar geleceğiz.",          pron: "Tek-rar ge-le-dsche-is",       cat: "urlaub", sub: "Bestellen" },
];

const CATEGORIES = [
  { id: "all",     label: "Alle",          icon: "📚" },
  { id: "basics",  label: "Basics",        icon: "💬" },
  { id: "urlaub",  label: "Urlaub",        icon: "🏖️" },
  { id: "alltag",  label: "Alltag",        icon: "🏠" },
];

const SUBCATEGORIES = [...new Set(VOCABULARY.map(v => v.sub))];
