const VOCABULARY = [
  // ─── BEGRÜSSUNGEN & BASICS ───────────────────────────────────────────────
  { id: 1,  de: "Hallo",                  tr: "Merhaba",              pron: "Mer-ha-ba",             cat: "basics",   sub: "Begrüßungen" },
  { id: 2,  de: "Guten Morgen",           tr: "Günaydın",             pron: "Gjün-aj-dın",           cat: "basics",   sub: "Begrüßungen" },
  { id: 3,  de: "Guten Tag",              tr: "İyi günler",           pron: "İyi gjün-ler",          cat: "basics",   sub: "Begrüßungen" },
  { id: 4,  de: "Guten Abend",            tr: "İyi akşamlar",         pron: "İyi ak-scham-lar",      cat: "basics",   sub: "Begrüßungen" },
  { id: 5,  de: "Gute Nacht",             tr: "İyi geceler",          pron: "İyi ge-dsche-ler",      cat: "basics",   sub: "Begrüßungen" },
  { id: 6,  de: "Auf Wiedersehen",        tr: "Hoşça kalın",          pron: "Hosch-tscha ka-lın",    cat: "basics",   sub: "Begrüßungen" },
  { id: 7,  de: "Tschüss",               tr: "Görüşürüz",            pron: "Gjö-rü-schü-rüs",       cat: "basics",   sub: "Begrüßungen" },
  { id: 8,  de: "Bitte",                  tr: "Lütfen",               pron: "Ljüt-fen",              cat: "basics",   sub: "Begrüßungen" },
  { id: 9,  de: "Danke",                  tr: "Teşekkür ederim",      pron: "Te-schek-kjür e-de-rim",cat: "basics",   sub: "Begrüßungen" },
  { id: 10, de: "Danke schön",            tr: "Çok teşekkürler",      pron: "Tschok te-schek-kjür-ler", cat: "basics", sub: "Begrüßungen" },
  { id: 11, de: "Bitte sehr / Gern geschehen", tr: "Rica ederim",     pron: "Ri-dscha e-de-rim",     cat: "basics",   sub: "Begrüßungen" },
  { id: 12, de: "Entschuldigung",         tr: "Özür dilerim",         pron: "Ö-sjür di-le-rim",      cat: "basics",   sub: "Begrüßungen" },
  { id: 13, de: "Ja",                     tr: "Evet",                 pron: "E-wet",                 cat: "basics",   sub: "Begrüßungen" },
  { id: 14, de: "Nein",                   tr: "Hayır",                pron: "Ha-jır",                cat: "basics",   sub: "Begrüßungen" },
  { id: 15, de: "Wie geht es Ihnen?",     tr: "Nasılsınız?",          pron: "Na-sıl-sı-nıs",         cat: "basics",   sub: "Begrüßungen" },
  { id: 16, de: "Mir geht es gut.",       tr: "İyiyim, teşekkürler.", pron: "İ-yi-jim, te-schek-kjür-ler", cat: "basics", sub: "Begrüßungen" },
  { id: 17, de: "Ich verstehe nicht.",    tr: "Anlamıyorum.",         pron: "An-la-mı-jo-rum",       cat: "basics",   sub: "Begrüßungen" },
  { id: 18, de: "Sprechen Sie Deutsch?",  tr: "Almanca biliyor musunuz?", pron: "Al-man-dscha bi-li-jor mu-su-nus", cat: "basics", sub: "Begrüßungen" },

  // ─── ZAHLEN ─────────────────────────────────────────────────────────────
  { id: 20, de: "0 – null",               tr: "sıfır",                pron: "sı-fır",                cat: "basics",   sub: "Zahlen" },
  { id: 21, de: "1 – eins",               tr: "bir",                  pron: "bir",                   cat: "basics",   sub: "Zahlen" },
  { id: 22, de: "2 – zwei",               tr: "iki",                  pron: "i-ki",                  cat: "basics",   sub: "Zahlen" },
  { id: 23, de: "3 – drei",               tr: "üç",                   pron: "ütsch",                 cat: "basics",   sub: "Zahlen" },
  { id: 24, de: "4 – vier",               tr: "dört",                 pron: "dört",                  cat: "basics",   sub: "Zahlen" },
  { id: 25, de: "5 – fünf",               tr: "beş",                  pron: "besch",                 cat: "basics",   sub: "Zahlen" },
  { id: 26, de: "6 – sechs",              tr: "altı",                 pron: "al-tı",                 cat: "basics",   sub: "Zahlen" },
  { id: 27, de: "7 – sieben",             tr: "yedi",                 pron: "je-di",                 cat: "basics",   sub: "Zahlen" },
  { id: 28, de: "8 – acht",               tr: "sekiz",                pron: "se-kis",                cat: "basics",   sub: "Zahlen" },
  { id: 29, de: "9 – neun",               tr: "dokuz",                pron: "do-kus",                cat: "basics",   sub: "Zahlen" },
  { id: 30, de: "10 – zehn",              tr: "on",                   pron: "on",                    cat: "basics",   sub: "Zahlen" },
  { id: 31, de: "20 – zwanzig",           tr: "yirmi",                pron: "jir-mi",                cat: "basics",   sub: "Zahlen" },
  { id: 32, de: "50 – fünfzig",           tr: "elli",                 pron: "el-li",                 cat: "basics",   sub: "Zahlen" },
  { id: 33, de: "100 – hundert",          tr: "yüz",                  pron: "jüs",                   cat: "basics",   sub: "Zahlen" },
  { id: 34, de: "1000 – tausend",         tr: "bin",                  pron: "bin",                   cat: "basics",   sub: "Zahlen" },

  // ─── WOCHENTAGE & ZEIT ───────────────────────────────────────────────────
  { id: 40, de: "Montag",                 tr: "Pazartesi",            pron: "Pa-sar-te-si",          cat: "basics",   sub: "Zeit" },
  { id: 41, de: "Dienstag",               tr: "Salı",                 pron: "Sa-lı",                 cat: "basics",   sub: "Zeit" },
  { id: 42, de: "Mittwoch",               tr: "Çarşamba",             pron: "Tschar-scham-ba",       cat: "basics",   sub: "Zeit" },
  { id: 43, de: "Donnerstag",             tr: "Perşembe",             pron: "Per-schem-be",          cat: "basics",   sub: "Zeit" },
  { id: 44, de: "Freitag",                tr: "Cuma",                 pron: "Dschu-ma",              cat: "basics",   sub: "Zeit" },
  { id: 45, de: "Samstag",                tr: "Cumartesi",            pron: "Dschu-mar-te-si",       cat: "basics",   sub: "Zeit" },
  { id: 46, de: "Sonntag",                tr: "Pazar",                pron: "Pa-sar",                cat: "basics",   sub: "Zeit" },
  { id: 47, de: "heute",                  tr: "bugün",                pron: "bu-gjün",               cat: "basics",   sub: "Zeit" },
  { id: 48, de: "morgen",                 tr: "yarın",                pron: "ja-rın",                cat: "basics",   sub: "Zeit" },
  { id: 49, de: "gestern",                tr: "dün",                  pron: "djün",                  cat: "basics",   sub: "Zeit" },
  { id: 50, de: "Wie spät ist es?",       tr: "Saat kaç?",            pron: "Sa-at katsch",          cat: "basics",   sub: "Zeit" },

  // ─── HOTEL ──────────────────────────────────────────────────────────────
  { id: 60, de: "Ich habe eine Reservierung.", tr: "Rezervasyonum var.", pron: "Re-ser-was-jo-num war", cat: "urlaub", sub: "Hotel" },
  { id: 61, de: "Ein Zimmer für zwei Personen", tr: "İki kişilik bir oda",  pron: "İki ki-schi-lik bir o-da", cat: "urlaub", sub: "Hotel" },
  { id: 62, de: "Doppelzimmer",           tr: "çift kişilik oda",     pron: "tschift ki-schi-lik o-da", cat: "urlaub", sub: "Hotel" },
  { id: 63, de: "Einzelzimmer",           tr: "tek kişilik oda",      pron: "tek ki-schi-lik o-da",  cat: "urlaub", sub: "Hotel" },
  { id: 64, de: "Frühstück inklusive?",   tr: "Kahvaltı dahil mi?",   pron: "Kah-wal-tı da-hil mi",  cat: "urlaub", sub: "Hotel" },
  { id: 65, de: "Wann ist Check-out?",    tr: "Check-out saati ne zaman?", pron: "Tschek-aut sa-a-ti ne sa-man", cat: "urlaub", sub: "Hotel" },
  { id: 66, de: "Der Schlüssel",          tr: "Anahtar",              pron: "An-ah-tar",             cat: "urlaub", sub: "Hotel" },
  { id: 67, de: "Das Handtuch",           tr: "Havlu",                pron: "Haw-lu",                cat: "urlaub", sub: "Hotel" },
  { id: 68, de: "Das Zimmer ist nicht sauber.", tr: "Oda temiz değil.", pron: "O-da te-mis de-jil",  cat: "urlaub", sub: "Hotel" },
  { id: 69, de: "Haben Sie WLAN?",        tr: "Wi-Fi var mı?",        pron: "Waj-faj war mı",        cat: "urlaub", sub: "Hotel" },
  { id: 70, de: "Ich möchte auschecken.", tr: "Check-out yapmak istiyorum.", pron: "Tschek-aut jap-mak is-ti-jo-rum", cat: "urlaub", sub: "Hotel" },

  // ─── RESTAURANT & ESSEN ──────────────────────────────────────────────────
  { id: 80, de: "Einen Tisch für zwei, bitte.", tr: "İki kişilik masa, lütfen.", pron: "İki ki-schi-lik ma-sa, ljüt-fen", cat: "urlaub", sub: "Restaurant" },
  { id: 81, de: "Die Speisekarte, bitte.",  tr: "Menü, lütfen.",        pron: "Me-njü, ljüt-fen",      cat: "urlaub", sub: "Restaurant" },
  { id: 82, de: "Was empfehlen Sie?",      tr: "Ne tavsiye edersiniz?", pron: "Ne taw-si-je e-der-si-nis", cat: "urlaub", sub: "Restaurant" },
  { id: 83, de: "Ich bin Vegetarier.",     tr: "Ben vejeteryenim.",    pron: "Ben we-dsche-ter-ja-nim", cat: "urlaub", sub: "Restaurant" },
  { id: 84, de: "Ohne Fleisch, bitte.",    tr: "Etsiz, lütfen.",       pron: "Et-sis, ljüt-fen",      cat: "urlaub", sub: "Restaurant" },
  { id: 85, de: "Die Rechnung, bitte.",    tr: "Hesap, lütfen.",       pron: "He-sap, ljüt-fen",      cat: "urlaub", sub: "Restaurant" },
  { id: 86, de: "Es hat sehr gut geschmeckt.", tr: "Çok lezzetliydi.", pron: "Tschok les-set-li-di",  cat: "urlaub", sub: "Restaurant" },
  { id: 87, de: "Wasser",                  tr: "Su",                   pron: "su",                    cat: "urlaub", sub: "Restaurant" },
  { id: 88, de: "Tee",                     tr: "Çay",                  pron: "tschaj",                cat: "urlaub", sub: "Restaurant" },
  { id: 89, de: "Kaffee",                  tr: "Kahve",                pron: "kah-we",                cat: "urlaub", sub: "Restaurant" },
  { id: 90, de: "Brot",                    tr: "Ekmek",                pron: "ek-mek",                cat: "urlaub", sub: "Restaurant" },
  { id: 91, de: "Fleisch",                 tr: "Et",                   pron: "et",                    cat: "urlaub", sub: "Restaurant" },
  { id: 92, de: "Fisch",                   tr: "Balık",                pron: "ba-lık",                cat: "urlaub", sub: "Restaurant" },
  { id: 93, de: "Gemüse",                  tr: "Sebze",                pron: "seb-se",                cat: "urlaub", sub: "Restaurant" },
  { id: 94, de: "lecker / köstlich",       tr: "lezzetli",             pron: "les-set-li",            cat: "urlaub", sub: "Restaurant" },
  { id: 95, de: "Guten Appetit!",          tr: "Afiyet olsun!",        pron: "A-fi-jet ol-sun",       cat: "urlaub", sub: "Restaurant" },

  // ─── STRAND & FREIZEIT ───────────────────────────────────────────────────
  { id: 100, de: "Das Meer",              tr: "Deniz",                 pron: "De-nis",                cat: "urlaub", sub: "Strand" },
  { id: 101, de: "Der Strand",            tr: "Sahil / Plaj",         pron: "Sa-hil / Pladsch",      cat: "urlaub", sub: "Strand" },
  { id: 102, de: "Wo ist das Meer?",      tr: "Deniz nerede?",        pron: "De-nis ne-re-de",       cat: "urlaub", sub: "Strand" },
  { id: 103, de: "Sonnencreme",           tr: "Güneş kremi",          pron: "Gjü-nesch kre-mi",      cat: "urlaub", sub: "Strand" },
  { id: 104, de: "Liegestuhl",            tr: "Şezlong",              pron: "Sches-long",            cat: "urlaub", sub: "Strand" },
  { id: 105, de: "Sonnenschirm",          tr: "Şemsiye",              pron: "Schem-si-je",           cat: "urlaub", sub: "Strand" },
  { id: 106, de: "schwimmen",             tr: "yüzmek",               pron: "jüs-mek",               cat: "urlaub", sub: "Strand" },
  { id: 107, de: "Das Schwimmbad",        tr: "Yüzme havuzu",         pron: "Jüs-me ha-wu-su",       cat: "urlaub", sub: "Strand" },
  { id: 108, de: "Es ist heiß.",          tr: "Hava çok sıcak.",      pron: "Ha-wa tschok sı-dschak", cat: "urlaub", sub: "Strand" },

  // ─── EINKAUFEN & MARKT ───────────────────────────────────────────────────
  { id: 110, de: "Wie viel kostet das?",  tr: "Bu ne kadar?",         pron: "Bu ne ka-dar",          cat: "urlaub", sub: "Einkaufen" },
  { id: 111, de: "Das ist zu teuer.",     tr: "Bu çok pahalı.",       pron: "Bu tschok pa-ha-lı",    cat: "urlaub", sub: "Einkaufen" },
  { id: 112, de: "Haben Sie etwas Günstigeres?", tr: "Daha ucuzu var mı?", pron: "Da-ha u-dschu-su war mı", cat: "urlaub", sub: "Einkaufen" },
  { id: 113, de: "Ich nehme das.",        tr: "Bunu alıyorum.",       pron: "Bu-nu a-lı-jo-rum",     cat: "urlaub", sub: "Einkaufen" },
  { id: 114, de: "Wo ist der Markt?",     tr: "Çarşı nerede?",        pron: "Tschar-schı ne-re-de",  cat: "urlaub", sub: "Einkaufen" },
  { id: 115, de: "Bargeld",               tr: "Nakit",                pron: "Na-kit",                cat: "urlaub", sub: "Einkaufen" },
  { id: 116, de: "Kreditkarte",           tr: "Kredi kartı",          pron: "Kre-di kar-tı",         cat: "urlaub", sub: "Einkaufen" },
  { id: 117, de: "Tüte / Beutel",         tr: "Poşet",                pron: "Po-schet",              cat: "urlaub", sub: "Einkaufen" },
  { id: 118, de: "Wo ist der Supermarkt?", tr: "Süpermarket nerede?", pron: "Sjü-per-mar-ket ne-re-de", cat: "urlaub", sub: "Einkaufen" },

  // ─── TRANSPORT ───────────────────────────────────────────────────────────
  { id: 120, de: "Wo ist der Bahnhof?",   tr: "Tren garı nerede?",    pron: "Tren ga-rı ne-re-de",   cat: "urlaub", sub: "Transport" },
  { id: 121, de: "Wo ist der Flughafen?", tr: "Havalimanı nerede?",   pron: "Ha-wa-li-ma-nı ne-re-de", cat: "urlaub", sub: "Transport" },
  { id: 122, de: "Ein Ticket nach Istanbul", tr: "İstanbul'a bir bilet", pron: "İs-tan-bu-la bir bi-let", cat: "urlaub", sub: "Transport" },
  { id: 123, de: "Wann fährt der Bus?",   tr: "Otobüs ne zaman kalkıyor?", pron: "O-to-bjüs ne sa-man kal-kı-jor", cat: "urlaub", sub: "Transport" },
  { id: 124, de: "Taxi!",                 tr: "Taksi!",               pron: "Tak-si",                cat: "urlaub", sub: "Transport" },
  { id: 125, de: "links",                 tr: "sol",                  pron: "sol",                   cat: "urlaub", sub: "Transport" },
  { id: 126, de: "rechts",                tr: "sağ",                  pron: "saa",                   cat: "urlaub", sub: "Transport" },
  { id: 127, de: "geradeaus",             tr: "düz git",              pron: "djüs git",              cat: "urlaub", sub: "Transport" },
  { id: 128, de: "Halten Sie hier, bitte.", tr: "Burada durun, lütfen.", pron: "Bu-ra-da du-run, ljüt-fen", cat: "urlaub", sub: "Transport" },

  // ─── NOTFÄLLE ────────────────────────────────────────────────────────────
  { id: 130, de: "Hilfe!",                tr: "İmdat!",               pron: "İm-dat",                cat: "urlaub", sub: "Notfälle" },
  { id: 131, de: "Arzt / Krankenhaus",    tr: "Doktor / Hastane",     pron: "Dok-tor / Has-ta-ne",   cat: "urlaub", sub: "Notfälle" },
  { id: 132, de: "Ich brauche einen Arzt.", tr: "Doktora ihtiyacım var.", pron: "Dok-to-ra ih-ti-ja-dschım war", cat: "urlaub", sub: "Notfälle" },
  { id: 133, de: "Rufen Sie die Polizei!", tr: "Polisi arayın!",      pron: "Po-li-si a-ra-jın",     cat: "urlaub", sub: "Notfälle" },
  { id: 134, de: "Ich habe meinen Pass verloren.", tr: "Pasaportumu kaybettim.", pron: "Pa-sa-por-tu-mu kaj-bet-tim", cat: "urlaub", sub: "Notfälle" },
  { id: 135, de: "Apotheke",              tr: "Eczane",               pron: "Edsch-sa-ne",           cat: "urlaub", sub: "Notfälle" },

  // ─── HAUSHALT & FAMILIE ──────────────────────────────────────────────────
  { id: 140, de: "Die Familie",           tr: "Aile",                 pron: "A-i-le",                cat: "alltag",  sub: "Familie" },
  { id: 141, de: "Mutter",                tr: "Anne",                 pron: "An-ne",                 cat: "alltag",  sub: "Familie" },
  { id: 142, de: "Vater",                 pron: "Ba-ba",              tr: "Baba",                    cat: "alltag",  sub: "Familie" },
  { id: 143, de: "Kind / Kinder",         tr: "Çocuk / Çocuklar",    pron: "Tscho-dschuk / Tscho-dschuk-lar", cat: "alltag", sub: "Familie" },
  { id: 144, de: "Bruder",                tr: "Erkek kardeş",         pron: "Er-kek kar-desch",      cat: "alltag",  sub: "Familie" },
  { id: 145, de: "Schwester",             tr: "Kız kardeş",           pron: "Kıs kar-desch",         cat: "alltag",  sub: "Familie" },
  { id: 146, de: "Großmutter",            tr: "Büyükanne",            pron: "Bjü-jük-an-ne",         cat: "alltag",  sub: "Familie" },
  { id: 147, de: "Großvater",             tr: "Büyükbaba",            pron: "Bjü-jük-ba-ba",         cat: "alltag",  sub: "Familie" },
  { id: 148, de: "Ehemann",               tr: "Koca / Eş",            pron: "Ko-dscha / Esch",       cat: "alltag",  sub: "Familie" },
  { id: 149, de: "Ehefrau",               tr: "Karı / Eş",            pron: "Ka-rı / Esch",          cat: "alltag",  sub: "Familie" },

  // ─── HAUSHALT & WOHNEN ───────────────────────────────────────────────────
  { id: 150, de: "Das Haus",              tr: "Ev",                   pron: "ew",                    cat: "alltag",  sub: "Wohnen" },
  { id: 151, de: "Die Küche",             tr: "Mutfak",               pron: "Mut-fak",               cat: "alltag",  sub: "Wohnen" },
  { id: 152, de: "Das Wohnzimmer",        tr: "Oturma odası",         pron: "O-tur-ma o-da-sı",      cat: "alltag",  sub: "Wohnen" },
  { id: 153, de: "Das Schlafzimmer",      tr: "Yatak odası",          pron: "Ja-tak o-da-sı",        cat: "alltag",  sub: "Wohnen" },
  { id: 154, de: "Das Badezimmer",        tr: "Banyo",                pron: "Ban-jo",                cat: "alltag",  sub: "Wohnen" },
  { id: 155, de: "Wasser",                tr: "Su",                   pron: "su",                    cat: "alltag",  sub: "Wohnen" },
  { id: 156, de: "Das Fenster",           tr: "Pencere",              pron: "Pen-dsche-re",          cat: "alltag",  sub: "Wohnen" },
  { id: 157, de: "Die Tür",               tr: "Kapı",                 pron: "Ka-pı",                 cat: "alltag",  sub: "Wohnen" },
  { id: 158, de: "Das Licht",             tr: "Işık",                 pron: "I-schık",               cat: "alltag",  sub: "Wohnen" },
  { id: 159, de: "Mach das Licht an.",    tr: "Işığı aç.",            pron: "I-schı-ı atsch",        cat: "alltag",  sub: "Wohnen" },

  // ─── ALLTAG & KOMMUNIKATION ──────────────────────────────────────────────
  { id: 160, de: "Ich bin müde.",         tr: "Yorgunum.",            pron: "Jor-gu-num",            cat: "alltag",  sub: "Alltag" },
  { id: 161, de: "Ich habe Hunger.",      tr: "Açım.",                pron: "a-tschım",              cat: "alltag",  sub: "Alltag" },
  { id: 162, de: "Ich habe Durst.",       tr: "Susadım.",             pron: "Su-sa-dım",             cat: "alltag",  sub: "Alltag" },
  { id: 163, de: "Was machst du?",        tr: "Ne yapıyorsun?",       pron: "Ne ja-pı-jor-sun",      cat: "alltag",  sub: "Alltag" },
  { id: 164, de: "Komm her!",             tr: "Gel buraya!",          pron: "Gel bu-ra-ja",          cat: "alltag",  sub: "Alltag" },
  { id: 165, de: "Warte kurz!",           tr: "Bir dakika!",          pron: "Bir da-ki-ka",          cat: "alltag",  sub: "Alltag" },
  { id: 166, de: "Ich liebe dich.",       tr: "Seni seviyorum.",      pron: "Se-ni se-wi-jo-rum",    cat: "alltag",  sub: "Alltag" },
  { id: 167, de: "Schau mal!",            tr: "Bak şuna!",            pron: "Bak schu-na",           cat: "alltag",  sub: "Alltag" },
  { id: 168, de: "Vorsicht!",             tr: "Dikkat!",              pron: "Dik-kat",               cat: "alltag",  sub: "Alltag" },
  { id: 169, de: "Kein Problem.",         tr: "Sorun değil.",         pron: "So-run de-jil",         cat: "alltag",  sub: "Alltag" },
  { id: 170, de: "Natürlich!",            tr: "Tabii ki!",            pron: "Ta-bi-i ki",            cat: "alltag",  sub: "Alltag" },
  { id: 171, de: "Vielleicht.",           tr: "Belki.",               pron: "Bel-ki",                cat: "alltag",  sub: "Alltag" },
  { id: 172, de: "Wann?",                 tr: "Ne zaman?",            pron: "Ne sa-man",             cat: "alltag",  sub: "Alltag" },
  { id: 173, de: "Wo?",                   tr: "Nerede?",              pron: "Ne-re-de",              cat: "alltag",  sub: "Alltag" },
  { id: 174, de: "Warum?",               tr: "Neden? / Niye?",       pron: "Ne-den / Ni-je",        cat: "alltag",  sub: "Alltag" },
  { id: 175, de: "Wie?",                  tr: "Nasıl?",               pron: "Na-sıl",                cat: "alltag",  sub: "Alltag" },

  // ─── KÖRPER & GESUNDHEIT ─────────────────────────────────────────────────
  { id: 180, de: "Ich bin krank.",        tr: "Hastayım.",            pron: "Has-ta-jım",            cat: "alltag",  sub: "Gesundheit" },
  { id: 181, de: "Mir ist schwindelig.",  tr: "Başım dönüyor.",       pron: "Ba-schım dö-njü-jor",   cat: "alltag",  sub: "Gesundheit" },
  { id: 182, de: "Ich habe Schmerzen.",   tr: "Ağrım var.",           pron: "Aa-rım war",            cat: "alltag",  sub: "Gesundheit" },
  { id: 183, de: "Kopfschmerzen",         tr: "Baş ağrısı",           pron: "Basch aa-rı-sı",        cat: "alltag",  sub: "Gesundheit" },
  { id: 184, de: "Magenschmerzen",        tr: "Mide ağrısı",          pron: "Mi-de aa-rı-sı",        cat: "alltag",  sub: "Gesundheit" },
  { id: 185, de: "Ich bin allergisch gegen...", tr: "...ye alerjim var.", pron: "...je a-ler-dschim war", cat: "alltag", sub: "Gesundheit" },
];

const CATEGORIES = [
  { id: "all",     label: "Alle",          icon: "📚" },
  { id: "basics",  label: "Basics",        icon: "💬" },
  { id: "urlaub",  label: "Urlaub",        icon: "🏖️" },
  { id: "alltag",  label: "Alltag",        icon: "🏠" },
];

const SUBCATEGORIES = [...new Set(VOCABULARY.map(v => v.sub))];
