const VOCABULARY = [
  // ─── BEGRÜSSUNGEN & BASICS ───────────────────────────────────────────────
  { id: 1,  de: "Hallo",                  tr: "Merhaba",              pron: "Mer-ha-ba",             cat: "basics",   sub: "Begrüßungen" },
  { id: 2,  de: "Guten Morgen",           tr: "Günaydın",             pron: "Gjün-aj-dın",           cat: "basics",   sub: "Begrüßungen" },
  { id: 3,  de: "Guten Tag",              tr: "İyi günler",           pron: "İyi gjün-ler",          cat: "basics",   sub: "Begrüßungen" },
  { id: 4,  de: "Guten Abend",            tr: "İyi akşamlar",         pron: "İyi ak-scham-lar",      cat: "basics",   sub: "Begrüßungen" },
  { id: 5,  de: "Gute Nacht",             tr: "İyi geceler",          pron: "İyi ge-dsche-ler",      cat: "basics",   sub: "Begrüßungen" },
  { id: 6,  de: "Auf Wiedersehen",        tr: "Hoşça kalın",          pron: "Hosch-tscha ka-lın",    cat: "basics",   sub: "Begrüßungen" },
  { id: 7,  de: "Tschüss",               tr: "Görüşürüz",            pron: "Gjö-rü-schü-rüs",       cat: "basics",   sub: "Begrüßungen" },
  { id: 8,  de: "Bitte",                  tr: "Lütfen",               pron: "Ljüt-fen",              cat: "basics",   sub: "Begrüßungen" },
  { id: 9,  de: "Danke",                  tr: "Teşekkür ederim",      pron: "Te-schek-kjür e-de-rim",cat: "basics",   sub: "Begrüßungen" },
  { id: 10, de: "Danke schön",            tr: "Çok teşekkürler",      pron: "Tschok te-schek-kjür-ler", cat: "basics", sub: "Begrüßungen" },
  { id: 11, de: "Bitte sehr / Gern geschehen", tr: "Rica ederim",     pron: "Ri-dscha e-de-rim",     cat: "basics",   sub: "Begrüßungen" },
  { id: 12, de: "Entschuldigung",         tr: "Özür dilerim",         pron: "Ö-sjür di-le-rim",      cat: "basics",   sub: "Begrüßungen" },
  { id: 13, de: "Ja",                     tr: "Evet",                 pron: "E-wet",                 cat: "basics",   sub: "Begrüßungen" },
  { id: 14, de: "Nein",                   tr: "Hayır",                pron: "Ha-jır",                cat: "basics",   sub: "Begrüßungen" },
  { id: 15, de: "Wie geht es Ihnen?",     tr: "Nasılsınız?",          pron: "Na-sıl-sı-nıs",         cat: "basics",   sub: "Begrüßungen" },
  { id: 16, de: "Mir geht es gut.",       tr: "İyiyim, teşekkürler.", pron: "İ-yi-jim, te-schek-kjür-ler", cat: "basics", sub: "Begrüßungen" },
  { id: 17, de: "Ich verstehe nicht.",    tr: "Anlamıyorum.",         pron: "An-la-mı-jo-rum",       cat: "basics",   sub: "Begrüßungen" },
  { id: 18, de: "Sprechen Sie Deutsch?",  tr: "Almanca biliyor musunuz?", pron: "Al-man-dscha bi-li-jor mu-su-nus", cat: "basics", sub: "Begrüßungen" },

  // ─── ZAHLEN ─────────────────────────────────────────────────────────────
  { id: 20, de: "0 – null",               tr: "sıfır",                pron: "sı-fır",                cat: "basics",   sub: "Zahlen" },
  { id: 21, de: "1 – eins",               tr: "bir",                  pron: "bir",                   cat: "basics",   sub: "Zahlen" },
  { id: 22, de: "2 – zwei",               tr: "iki",                  pron: "i-ki",                  cat: "basics",   sub: "Zahlen" },
  { id: 23, de: "3 – drei",               tr: "üç",                   pron: "ütsch",                 cat: "basics",   sub: "Zahlen" },
  { id: 24, de: "4 – vier",               tr: "dört",                 pron: "dört",                  cat: "basics",   sub: "Zahlen" },
  { id: 25, de: "5 – fünf",               tr: "beş",                  pron: "besch",                 cat: "basics",   sub: "Zahlen" },
  { id: 26, de: "6 – sechs",              tr: "altı",                 pron: "al-tı",                 cat: "basics",   sub: "Zahlen" },
  { id: 27, de: "7 – sieben",             tr: "yedi",                 pron: "je-di",                 cat: "basics",   sub: "Zahlen" },
  { id: 28, de: "8 – acht",               tr: "sekiz",                pron: "se-kis",                cat: "basics",   sub: "Zahlen" },
  { id: 29, de: "9 – neun",               tr: "dokuz",                pron: "do-kus",                cat: "basics",   sub: "Zahlen" },
  { id: 30, de: "10 – zehn",              tr: "on",                   pron: "on",                    cat: "basics",   sub: "Zahlen" },
  { id: 31, de: "20 – zwanzig",           tr: "yirmi",                pron: "jir-mi",                cat: "basics",   sub: "Zahlen" },
  { id: 32, de: "50 – fünfzig",           tr: "elli",                 pron: "el-li",                 cat: "basics",   sub: "Zahlen" },
  { id: 33, de: "100 – hundert",          tr: "yüz",                  pron: "jüs",                   cat: "basics",   sub: "Zahlen" },
  { id: 34, de: "1000 – tausend",         tr: "bin",                  pron: "bin",                   cat: "basics",   sub: "Zahlen" },

  // ─── WOCHENTAGE & ZEIT ───────────────────────────────────────────────────
  { id: 40, de: "Montag",                 tr: "Pazartesi",            pron: "Pa-sar-te-si",          cat: "basics",   sub: "Zeit" },
  { id: 41, de: "Dienstag",               tr: "Salı",                 pron: "Sa-lı",                 cat: "basics",   sub: "Zeit" },
  { id: 42, de: "Mittwoch",               tr: "Çarşamba",             pron: "Tschar-scham-ba",       cat: "basics",   sub: "Zeit" },
  { id: 43, de: "Donnerstag",             tr: "Perşembe",             pron: "Per-schem-be",          cat: "basics",   sub: "Zeit" },
  { id: 44, de: "Freitag",                tr: "Cuma",                 pron: "Dschu-ma",              cat: "basics",   sub: "Zeit" },
  { id: 45, de: "Samstag",                tr: "Cumartesi",            pron: "Dschu-mar-te-si",       cat: "basics",   sub: "Zeit" },
  { id: 46, de: "Sonntag",                tr: "Pazar",                pron: "Pa-sar",                cat: "basics",   sub: "Zeit" },
  { id: 47, de: "heute",                  tr: "bugün",                pron: "bu-gjün",               cat: "basics",   sub: "Zeit" },
  { id: 48, de: "morgen",                 tr: "yarın",                pron: "ja-rın",                cat: "basics",   sub: "Zeit" },
  { id: 49, de: "gestern",                tr: "dün",                  pron: "djün",                  cat: "basics",   sub: "Zeit" },
  { id: 50, de: "Wie spät ist es?",       tr: "Saat kaç?",            pron: "Sa-at katsch",          cat: "basics",   sub: "Zeit" },

  // ─── HOTEL ──────────────────────────────────────────────────────────────
  { id: 60, de: "Ich habe eine Reservierung.", tr: "Rezervasyonum var.", pron: "Re-ser-was-jo-num war", cat: "urlaub", sub: "Hotel" },
  { id: 61, de: "Ein Zimmer für zwei Personen", tr: "İki kişilik bir oda",  pron: "İki ki-schi-lik bir o-da", cat: "urlaub", sub: "Hotel" },
  { id: 62, de: "Doppelzimmer",           tr: "çift kişilik oda",     pron: "tschift ki-schi-lik o-da", cat: "urlaub", sub: "Hotel" },
  { id: 63, de: "Einzelzimmer",           tr: "tek kişilik oda",      pron: "tek ki-schi-lik o-da",  cat: "urlaub", sub: "Hotel" },
  { id: 64, de: "Frühstück inklusive?",   tr: "Kahvaltı dahil mi?",   pron: "Kah-wal-tı da-hil mi",  cat: "urlaub", sub: "Hotel" },
  { id: 65, de: "Wann ist Check-out?",    tr: "Check-out saati ne zaman?", pron: "Tschek-aut sa-a-ti ne sa-man", cat: "urlaub", sub: "Hotel" },
  { id: 66, de: "Der Schlüssel",          tr: "Anahtar",              pron: "An-ah-tar",             cat: "urlaub", sub: "Hotel" },
  { id: 67, de: "Das Handtuch",           tr: "Havlu",                pron: "Haw-lu",                cat: "urlaub", sub: "Hotel" },
  { id: 68, de: "Das Zimmer ist nicht sauber.", tr: "Oda temiz değil.", pron: "O-da te-mis de-jil",  cat: "urlaub", sub: "Hotel" },
  { id: 69, de: "Haben Sie WLAN?",        tr: "Wi-Fi var mı?",        pron: "Waj-faj war mı",        cat: "urlaub", sub: "Hotel" },
  { id: 70, de: "Ich möchte auschecken.", tr: "Check-out yapmak istiyorum.", pron: "Tschek-aut jap-mak is-ti-jo-rum", cat: "urlaub", sub: "Hotel" },

  // ─── RESTAURANT & ESSEN ──────────────────────────────────────────────────
  { id: 80, de: "Einen Tisch für zwei, bitte.", tr: "İki kişilik masa, lütfen.", pron: "İki ki-schi-lik ma-sa, ljüt-fen", cat: "urlaub", sub: "Restaurant" },
  { id: 81, de: "Die Speisekarte, bitte.",  tr: "Menü, lütfen.",        pron: "Me-njü, ljüt-fen",      cat: "urlaub", sub: "Restaurant" },
  { id: 82, de: "Was empfehlen Sie?",      tr: "Ne tavsiye edersiniz?", pron: "Ne taw-si-je e-der-si-nis", cat: "urlaub", sub: "Restaurant" },
  { id: 83, de: "Ich bin Vegetarier.",     tr: "Ben vejeteryenim.",    pron: "Ben we-dsche-ter-ja-nim", cat: "urlaub", sub: "Restaurant" },
  { id: 84, de: "Ohne Fleisch, bitte.",    tr: "Etsiz, lütfen.",       pron: "Et-sis, ljüt-fen",      cat: "urlaub", sub: "Restaurant" },
  { id: 85, de: "Die Rechnung, bitte.",    tr: "Hesap, lütfen.",       pron: "He-sap, ljüt-fen",      cat: "urlaub", sub: "Restaurant" },
  { id: 86, de: "Es hat sehr gut geschmeckt.", tr: "Çok lezzetliydi.", pron: "Tschok les-set-li-di",  cat: "urlaub", sub: "Restaurant" },
  { id: 87, de: "Wasser",                  tr: "Su",                   pron: "su",                    cat: "urlaub", sub: "Restaurant" },
  { id: 88, de: "Tee",                     tr: "Çay",                  pron: "tschaj",                cat: "urlaub", sub: "Restaurant" },
  { id: 89, de: "Kaffee",                  tr: "Kahve",                pron: "kah-we",                cat: "urlaub", sub: "Restaurant" },
  { id: 90, de: "Brot",                    tr: "Ekmek",                pron: "ek-mek",                cat: "urlaub", sub: "Restaurant" },
  { id: 91, de: "Fleisch",                 tr: "Et",                   pron: "et",                    cat: "urlaub", sub: "Restaurant" },
  { id: 92, de: "Fisch",                   tr: "Balık",                pron: "ba-lık",                cat: "urlaub", sub: "Restaurant" },
  { id: 93, de: "Gemüse",                  tr: "Sebze",                pron: "seb-se",                cat: "urlaub", sub: "Restaurant" },
  { id: 94, de: "lecker / köstlich",       tr: "lezzetli",             pron: "les-set-li",            cat: "urlaub", sub: "Restaurant" },
  { id: 95, de: "Guten Appetit!",          tr: "Afiyet olsun!",        pron: "A-fi-jet ol-sun",       cat: "urlaub", sub: "Restaurant" },

  // ─── STRAND & FREIZEIT ───────────────────────────────────────────────────
  { id: 100, de: "Das Meer",              tr: "Deniz",                 pron: "De-nis",                cat: "urlaub", sub: "Strand" },
  { id: 101, de: "Der Strand",            tr: "Sahil / Plaj",         pron: "Sa-hil / Pladsch",      cat: "urlaub", sub: "Strand" },
  { id: 102, de: "Wo ist das Meer?",      tr: "Deniz nerede?",        pron: "De-nis ne-re-de",       cat: "urlaub", sub: "Strand" },
  { id: 103, de: "Sonnencreme",           tr: "Güneş kremi",          pron: "Gjü-nesch kre-mi",      cat: "urlaub", sub: "Strand" },
  { id: 104, de: "Liegestuhl",            tr: "Şezlong",              pron: "Sches-long",            cat: "urlaub", sub: "Strand" },
  { id: 105, de: "Sonnenschirm",          tr: "Şemsiye",              pron: "Schem-si-je",           cat: "urlaub", sub: "Strand" },
  { id: 106, de: "schwimmen",             tr: "yüzmek",               pron: "jüs-mek",               cat: "urlaub", sub: "Strand" },
  { id: 107, de: "Das Schwimmbad",        tr: "Yüzme havuzu",         pron: "Jüs-me ha-wu-su",       cat: "urlaub", sub: "Strand" },
  { id: 108, de: "Es ist heiß.",          tr: "Hava çok sıcak.",      pron: "Ha-wa tschok sı-dschak", cat: "urlaub", sub: "Strand" },

  // ─── EINKAUFEN & MARKT ───────────────────────────────────────────────────
  { id: 110, de: "Wie viel kostet das?",  tr: "Bu ne kadar?",         pron: "Bu ne ka-dar",          cat: "urlaub", sub: "Einkaufen" },
  { id: 111, de: "Das ist zu teuer.",     tr: "Bu çok pahalı.",       pron: "Bu tschok pa-ha-lı",    cat: "urlaub", sub: "Einkaufen" },
  { id: 112, de: "Haben Sie etwas Günstigeres?", tr: "Daha ucuzu var mı?", pron: "Da-ha u-dschu-su war mı", cat: "urlaub", sub: "Einkaufen" },
  { id: 113, de: "Ich nehme das.",        tr: "Bunu alıyorum.",       pron: "Bu-nu a-lı-jo-rum",     cat: "urlaub", sub: "Einkaufen" },
  { id: 114, de: "Wo ist der Markt?",     tr: "Çarşı nerede?",        pron: "Tschar-schı ne-re-de",  cat: "urlaub", sub: "Einkaufen" },
  { id: 115, de: "Bargeld",               tr: "Nakit",                pron: "Na-kit",                cat: "urlaub", sub: "Einkaufen" },
  { id: 116, de: "Kreditkarte",           tr: "Kredi kartı",          pron: "Kre-di kar-tı",         cat: "urlaub", sub: "Einkaufen" },
  { id: 117, de: "Tüte / Beutel",         tr: "Poşet",                pron: "Po-schet",              cat: "urlaub", sub: "Einkaufen" },
  { id: 118, de: "Wo ist der Supermarkt?", tr: "Süpermarket nerede?", pron: "Sjü-per-mar-ket ne-re-de", cat: "urlaub", sub: "Einkaufen" },

  // ─── TRANSPORT ───────────────────────────────────────────────────────────
  { id: 120, de: "Wo ist der Bahnhof?",   tr: "Tren garı nerede?",    pron: "Tren ga-rı ne-re-de",   cat: "urlaub", sub: "Transport" },
  { id: 121, de: "Wo ist der Flughafen?", tr: "Havalimanı nerede?",   pron: "Ha-wa-li-ma-nı ne-re-de", cat: "urlaub", sub: "Transport" },
  { id: 122, de: "Ein Ticket nach Istanbul", tr: "İstanbul'a bir bilet", pron: "İs-tan-bu-la bir bi-let", cat: "urlaub", sub: "Transport" },
  { id: 123, de: "Wann fährt der Bus?",   tr: "Otobüs ne zaman kalkıyor?", pron: "O-to-bjüs ne sa-man kal-kı-jor", cat: "urlaub", sub: "Transport" },
  { id: 124, de: "Taxi!",                 tr: "Taksi!",               pron: "Tak-si",                cat: "urlaub", sub: "Transport" },
  { id: 125, de: "links",                 tr: "sol",                  pron: "sol",                   cat: "urlaub", sub: "Transport" },
  { id: 126, de: "rechts",                tr: "sağ",                  pron: "saa",                   cat: "urlaub", sub: "Transport" },
  { id: 127, de: "geradeaus",             tr: "düz git",              pron: "djüs git",              cat: "urlaub", sub: "Transport" },
  { id: 128, de: "Halten Sie hier, bitte.", tr: "Burada durun, lütfen.", pron: "Bu-ra-da du-run, ljüt-fen", cat: "urlaub", sub: "Transport" },

  // ─── NOTFÄLLE ────────────────────────────────────────────────────────────
  { id: 130, de: "Hilfe!",                tr: "İmdat!",               pron: "İm-dat",                cat: "urlaub", sub: "Notfälle" },
  { id: 131, de: "Arzt / Krankenhaus",    tr: "Doktor / Hastane",     pron: "Dok-tor / Has-ta-ne",   cat: "urlaub", sub: "Notfälle" },
  { id: 132, de: "Ich brauche einen Arzt.", tr: "Doktora ihtiyacım var.", pron: "Dok-to-ra ih-ti-ja-dschım war", cat: "urlaub", sub: "Notfälle" },
  { id: 133, de: "Rufen Sie die Polizei!", tr: "Polisi arayın!",      pron: "Po-li-si a-ra-jın",     cat: "urlaub", sub: "Notfälle" },
  { id: 134, de: "Ich habe meinen Pass verloren.", tr: "Pasaportumu kaybettim.", pron: "Pa-sa-por-tu-mu kaj-bet-tim", cat: "urlaub", sub: "Notfälle" },
  { id: 135, de: "Apotheke",              tr: "Eczane",               pron: "Edsch-sa-ne",           cat: "urlaub", sub: "Notfälle" },

  // ─── HAUSHALT & FAMILIE ──────────────────────────────────────────────────
  { id: 140, de: "Die Familie",           tr: "Aile",                 pron: "A-i-le",                cat: "alltag",  sub: "Familie" },
  { id: 141, de: "Mutter",                tr: "Anne",                 pron: "An-ne",                 cat: "alltag",  sub: "Familie" },
  { id: 142, de: "Vater",                 pron: "Ba-ba",              tr: "Baba",                    cat: "alltag",  sub: "Familie" },
  { id: 143, de: "Kind / Kinder",         tr: "Çocuk / Çocuklar",    pron: "Tscho-dschuk / Tscho-dschuk-lar", cat: "alltag", sub: "Familie" },
  { id: 144, de: "Bruder",                tr: "Erkek kardeş",         pron: "Er-kek kar-desch",      cat: "alltag",  sub: "Familie" },
  { id: 145, de: "Schwester",             tr: "Kız kardeş",           pron: "Kıs kar-desch",         cat: "alltag",  sub: "Familie" },
  { id: 146, de: "Großmutter",            tr: "Büyükanne",            pron: "Bjü-jük-an-ne",         cat: "alltag",  sub: "Familie" },
  { id: 147, de: "Großvater",             tr: "Büyükbaba",            pron: "Bjü-jük-ba-ba",         cat: "alltag",  sub: "Familie" },
  { id: 148, de: "Ehemann",               tr: "Koca / Eş",            pron: "Ko-dscha / Esch",       cat: "alltag",  sub: "Familie" },
  { id: 149, de: "Ehefrau",               tr: "Karı / Eş",            pron: "Ka-rı / Esch",          cat: "alltag",  sub: "Familie" },

  // ─── HAUSHALT & WOHNEN ───────────────────────────────────────────────────
  { id: 150, de: "Das Haus",              tr: "Ev",                   pron: "ew",                    cat: "alltag",  sub: "Wohnen" },
  { id: 151, de: "Die Küche",             tr: "Mutfak",               pron: "Mut-fak",               cat: "alltag",  sub: "Wohnen" },
  { id: 152, de: "Das Wohnzimmer",        tr: "Oturma odası",         pron: "O-tur-ma o-da-sı",      cat: "alltag",  sub: "Wohnen" },
  { id: 153, de: "Das Schlafzimmer",      tr: "Yatak odası",          pron: "Ja-tak o-da-sı",        cat: "alltag",  sub: "Wohnen" },
  { id: 154, de: "Das Badezimmer",        tr: "Banyo",                pron: "Ban-jo",                cat: "alltag",  sub: "Wohnen" },
  { id: 155, de: "Wasser",                tr: "Su",                   pron: "su",                    cat: "alltag",  sub: "Wohnen" },
  { id: 156, de: "Das Fenster",           tr: "Pencere",              pron: "Pen-dsche-re",          cat: "alltag",  sub: "Wohnen" },
  { id: 157, de: "Die Tür",               tr: "Kapı",                 pron: "Ka-pı",                 cat: "alltag",  sub: "Wohnen" },
  { id: 158, de: "Das Licht",             tr: "Işık",                 pron: "I-schık",               cat: "alltag",  sub: "Wohnen" },
  { id: 159, de: "Mach das Licht an.",    tr: "Işığı aç.",            pron: "I-schı-ı atsch",        cat: "alltag",  sub: "Wohnen" },

  // ─── ALLTAG & KOMMUNIKATION ──────────────────────────────────────────────
  { id: 160, de: "Ich bin müde.",         tr: "Yorgunum.",            pron: "Jor-gu-num",            cat: "alltag",  sub: "Alltag" },
  { id: 161, de: "Ich habe Hunger.",      tr: "Açım.",                pron: "a-tschım",              cat: "alltag",  sub: "Alltag" },
  { id: 162, de: "Ich habe Durst.",       tr: "Susadım.",             pron: "Su-sa-dım",             cat: "alltag",  sub: "Alltag" },
  { id: 163, de: "Was machst du?",        tr: "Ne yapıyorsun?",       pron: "Ne ja-pı-jor-sun",      cat: "alltag",  sub: "Alltag" },
  { id: 164, de: "Komm her!",             tr: "Gel buraya!",          pron: "Gel bu-ra-ja",          cat: "alltag",  sub: "Alltag" },
  { id: 165, de: "Warte kurz!",           tr: "Bir dakika!",          pron: "Bir da-ki-ka",          cat: "alltag",  sub: "Alltag" },
  { id: 166, de: "Ich liebe dich.",       tr: "Seni seviyorum.",      pron: "Se-ni se-wi-jo-rum",    cat: "alltag",  sub: "Alltag" },
  { id: 167, de: "Schau mal!",            tr: "Bak şuna!",            pron: "Bak schu-na",           cat: "alltag",  sub: "Alltag" },
  { id: 168, de: "Vorsicht!",             tr: "Dikkat!",              pron: "Dik-kat",               cat: "alltag",  sub: "Alltag" },
  { id: 169, de: "Kein Problem.",         tr: "Sorun değil.",         pron: "So-run de-jil",         cat: "alltag",  sub: "Alltag" },
  { id: 170, de: "Natürlich!",            tr: "Tabii ki!",            pron: "Ta-bi-i ki",            cat: "alltag",  sub: "Alltag" },
  { id: 171, de: "Vielleicht.",           tr: "Belki.",               pron: "Bel-ki",                cat: "alltag",  sub: "Alltag" },
  { id: 172, de: "Wann?",                 tr: "Ne zaman?",            pron: "Ne sa-man",             cat: "alltag",  sub: "Alltag" },
  { id: 173, de: "Wo?",                   tr: "Nerede?",              pron: "Ne-re-de",              cat: "alltag",  sub: "Alltag" },
  { id: 174, de: "Warum?",               tr: "Neden? / Niye?",       pron: "Ne-den / Ni-je",        cat: "alltag",  sub: "Alltag" },
  { id: 175, de: "Wie?",                  tr: "Nasıl?",               pron: "Na-sıl",                cat: "alltag",  sub: "Alltag" },

  // ─── KÖRPER & GESUNDHEIT ─────────────────────────────────────────────────
  { id: 180, de: "Ich bin krank.",        tr: "Hastayım.",            pron: "Has-ta-jım",            cat: "alltag",  sub: "Gesundheit" },
  { id: 181, de: "Mir ist schwindelig.",  tr: "Başım dönüyor.",       pron: "Ba-schım dö-njü-jor",   cat: "alltag",  sub: "Gesundheit" },
  { id: 182, de: "Ich habe Schmerzen.",   tr: "Ağrım var.",           pron: "Aa-rım war",            cat: "alltag",  sub: "Gesundheit" },
  { id: 183, de: "Kopfschmerzen",         tr: "Baş ağrısı",           pron: "Basch aa-rı-sı",        cat: "alltag",  sub: "Gesundheit" },
  { id: 184, de: "Magenschmerzen",        tr: "Mide ağrısı",          pron: "Mi-de aa-rı-sı",        cat: "alltag",  sub: "Gesundheit" },
  { id: 185, de: "Ich bin allergisch gegen...", tr: "...ye alerjim var.", pron: "...je a-ler-dschim war", cat: "alltag", sub: "Gesundheit" },

  // ─── ZAHLEN ERWEITERT ────────────────────────────────────────────────────
  { id: 200, de: "11 – elf",               tr: "on bir",           pron: "on bir",              cat: "basics", sub: "Zahlen" },
  { id: 201, de: "12 – zwölf",             tr: "on iki",           pron: "on i-ki",             cat: "basics", sub: "Zahlen" },
  { id: 202, de: "13 – dreizehn",          tr: "on üç",            pron: "on ütsch",            cat: "basics", sub: "Zahlen" },
  { id: 203, de: "14 – vierzehn",          tr: "on dört",          pron: "on dört",             cat: "basics", sub: "Zahlen" },
  { id: 204, de: "15 – fünfzehn",          tr: "on beş",           pron: "on besch",            cat: "basics", sub: "Zahlen" },
  { id: 205, de: "16 – sechzehn",          tr: "on altı",          pron: "on al-tı",            cat: "basics", sub: "Zahlen" },
  { id: 206, de: "17 – siebzehn",          tr: "on yedi",          pron: "on je-di",            cat: "basics", sub: "Zahlen" },
  { id: 207, de: "18 – achtzehn",          tr: "on sekiz",         pron: "on se-kis",           cat: "basics", sub: "Zahlen" },
  { id: 208, de: "19 – neunzehn",          tr: "on dokuz",         pron: "on do-kus",           cat: "basics", sub: "Zahlen" },
  { id: 209, de: "25 – fünfundzwanzig",    tr: "yirmi beş",        pron: "jir-mi besch",        cat: "basics", sub: "Zahlen" },
  { id: 210, de: "30 – dreißig",           tr: "otuz",             pron: "o-tus",               cat: "basics", sub: "Zahlen" },
  { id: 211, de: "40 – vierzig",           tr: "kırk",             pron: "kırk",                cat: "basics", sub: "Zahlen" },
  { id: 212, de: "60 – sechzig",           tr: "altmış",           pron: "alt-mısch",           cat: "basics", sub: "Zahlen" },
  { id: 213, de: "70 – siebzig",           tr: "yetmiş",           pron: "jet-misch",           cat: "basics", sub: "Zahlen" },
  { id: 214, de: "80 – achtzig",           tr: "seksen",           pron: "sek-sen",             cat: "basics", sub: "Zahlen" },
  { id: 215, de: "90 – neunzig",           tr: "doksan",           pron: "dok-san",             cat: "basics", sub: "Zahlen" },
  { id: 216, de: "150 – hundertfünfzig",   tr: "yüz elli",         pron: "jüs el-li",           cat: "basics", sub: "Zahlen" },
  { id: 217, de: "200 – zweihundert",      tr: "iki yüz",          pron: "i-ki jüs",            cat: "basics", sub: "Zahlen" },
  { id: 218, de: "300 – dreihundert",      tr: "üç yüz",           pron: "ütsch jüs",           cat: "basics", sub: "Zahlen" },
  { id: 219, de: "500 – fünfhundert",      tr: "beş yüz",          pron: "besch jüs",           cat: "basics", sub: "Zahlen" },
  { id: 220, de: "750 – siebenhundertfünfzig", tr: "yedi yüz elli", pron: "je-di jüs el-li",   cat: "basics", sub: "Zahlen" },
  { id: 221, de: "1.500 – eintausendfünfhundert", tr: "bin beş yüz", pron: "bin besch jüs",    cat: "basics", sub: "Zahlen" },
  { id: 222, de: "2.000 – zweitausend",    tr: "iki bin",          pron: "i-ki bin",            cat: "basics", sub: "Zahlen" },
  { id: 223, de: "5.000 – fünftausend",    tr: "beş bin",          pron: "besch bin",           cat: "basics", sub: "Zahlen" },
  { id: 224, de: "10.000 – zehntausend",   tr: "on bin",           pron: "on bin",              cat: "basics", sub: "Zahlen" },
  { id: 225, de: "eine halbe",             tr: "yarım",            pron: "ja-rım",              cat: "basics", sub: "Zahlen" },
  { id: 226, de: "erste/r/s",             tr: "birinci",           pron: "bi-rin-dshi",         cat: "basics", sub: "Zahlen" },
  { id: 227, de: "zweite/r/s",            tr: "ikinci",            pron: "i-kin-dshi",          cat: "basics", sub: "Zahlen" },
  { id: 228, de: "dritte/r/s",            tr: "üçüncü",            pron: "ü-tschün-dshü",       cat: "basics", sub: "Zahlen" },

  // ─── BEZAHLEN ────────────────────────────────────────────────────────────
  { id: 230, de: "Was macht das insgesamt?",     tr: "Toplam ne kadar?",          pron: "Top-lam ne ka-dar",            cat: "urlaub", sub: "Bezahlen" },
  { id: 231, de: "Das macht 50 Euro.",            tr: "Elli euro eder.",            pron: "El-li eu-ro e-der",            cat: "urlaub", sub: "Bezahlen" },
  { id: 232, de: "Nehmen Sie Kreditkarte?",       tr: "Kredi kartı geçer mi?",      pron: "Kre-di kar-tı ge-tscher mi",   cat: "urlaub", sub: "Bezahlen" },
  { id: 233, de: "Bar oder Karte?",               tr: "Nakit mi, kart mı?",         pron: "Na-kit mi, kart mı",           cat: "urlaub", sub: "Bezahlen" },
  { id: 234, de: "Stimmt so. (Kein Rest.)",       tr: "Üstü kalsın.",               pron: "Üs-tü kal-sın",               cat: "urlaub", sub: "Bezahlen" },
  { id: 235, de: "Das Wechselgeld",               tr: "Para üstü",                  pron: "Pa-ra üs-tü",                  cat: "urlaub", sub: "Bezahlen" },
  { id: 236, de: "Kleingeld",                     tr: "Bozuk para",                 pron: "Bo-suk pa-ra",                 cat: "urlaub", sub: "Bezahlen" },
  { id: 237, de: "Haben Sie Kleingeld?",          tr: "Bozuk paranız var mı?",      pron: "Bo-suk pa-ra-nıs war mı",     cat: "urlaub", sub: "Bezahlen" },
  { id: 238, de: "Die Quittung / Der Bon",        tr: "Fiş / Makbuz",               pron: "Fisch / Mak-bus",              cat: "urlaub", sub: "Bezahlen" },
  { id: 239, de: "Quittung bitte.",               tr: "Fiş lütfen.",                pron: "Fisch ljüt-fen",               cat: "urlaub", sub: "Bezahlen" },
  { id: 240, de: "Kostenlos / Gratis",            tr: "Ücretsiz / Bedava",          pron: "Üdsch-ret-sis / Be-da-wa",     cat: "urlaub", sub: "Bezahlen" },
  { id: 241, de: "Gibt es Rabatt?",               tr: "İndirim var mı?",            pron: "İn-di-rim war mı",             cat: "urlaub", sub: "Bezahlen" },
  { id: 242, de: "Ich habe kein Bargeld.",        tr: "Nakit param yok.",           pron: "Na-kit pa-ram jok",            cat: "urlaub", sub: "Bezahlen" },
  { id: 243, de: "Zu teuer.",                     tr: "Çok pahalı.",                pron: "Tschok pa-ha-lı",              cat: "urlaub", sub: "Bezahlen" },
  { id: 244, de: "Der Preis / Was kostet das?",   tr: "Fiyat / Fiyatı ne kadar?",  pron: "Fi-jat / Fi-ja-tı ne ka-dar", cat: "urlaub", sub: "Bezahlen" },
  { id: 245, de: "Getrennt bezahlen.",            tr: "Ayrı ayrı ödeyeceğiz.",      pron: "Aj-rı aj-rı ö-de-je-dshis",  cat: "urlaub", sub: "Bezahlen" },
  { id: 246, de: "Zusammen bezahlen.",            tr: "Birlikte ödeyeceğiz.",       pron: "Bir-lik-te ö-de-je-dshis",    cat: "urlaub", sub: "Bezahlen" },

  // ─── PRAKTISCHE SÄTZE ────────────────────────────────────────────────────
  { id: 250, de: "Geht das? / Ist das möglich?", tr: "Olur mu?",                   pron: "O-lur mu",                     cat: "basics", sub: "Praktisch" },
  { id: 251, de: "Nicht möglich / Geht nicht.",  tr: "Olmaz.",                     pron: "Ol-mas",                       cat: "basics", sub: "Praktisch" },
  { id: 252, de: "Ich weiß nicht.",              tr: "Bilmiyorum.",                 pron: "Bil-mi-jo-rum",                cat: "basics", sub: "Praktisch" },
  { id: 253, de: "Ich habe verstanden.",         tr: "Anladım.",                    pron: "An-la-dım",                    cat: "basics", sub: "Praktisch" },
  { id: 254, de: "Langsamer, bitte.",            tr: "Daha yavaş, lütfen.",         pron: "Da-ha ja-wasch, ljüt-fen",     cat: "basics", sub: "Praktisch" },
  { id: 255, de: "Können Sie das aufschreiben?", tr: "Yazabilir misiniz?",          pron: "Ja-sa-bi-lir mi-si-nis",       cat: "basics", sub: "Praktisch" },
  { id: 256, de: "Wie heißen Sie?",             tr: "Adınız ne?",                  pron: "A-dı-nıs ne",                  cat: "basics", sub: "Praktisch" },
  { id: 257, de: "Ich heiße ...",               tr: "Adım ...",                    pron: "A-dım",                        cat: "basics", sub: "Praktisch" },
  { id: 258, de: "Woher kommen Sie?",           tr: "Nerelisiniz?",                pron: "Ne-re-li-si-nis",              cat: "basics", sub: "Praktisch" },
  { id: 259, de: "Ich komme aus Deutschland.",  tr: "Almanya'danım.",              pron: "Al-man-ja-da-nım",             cat: "basics", sub: "Praktisch" },
  { id: 260, de: "Ich suche ...",               tr: "... arıyorum.",               pron: "a-rı-jo-rum",                  cat: "basics", sub: "Praktisch" },
  { id: 261, de: "Gibt es hier ...?",           tr: "Burada ... var mı?",          pron: "Bu-ra-da ... war mı",          cat: "basics", sub: "Praktisch" },
  { id: 262, de: "Wie weit ist es?",            tr: "Ne kadar uzak?",              pron: "Ne ka-dar u-sak",              cat: "basics", sub: "Praktisch" },
  { id: 263, de: "Offen / Geöffnet",            tr: "Açık",                        pron: "A-tschık",                     cat: "basics", sub: "Praktisch" },
  { id: 264, de: "Geschlossen",                 tr: "Kapalı",                      pron: "Ka-pa-lı",                     cat: "basics", sub: "Praktisch" },
  { id: 265, de: "Wann öffnet es?",             tr: "Ne zaman açılıyor?",          pron: "Ne sa-man a-tschı-lı-jor",    cat: "basics", sub: "Praktisch" },
  { id: 266, de: "Wann schließt es?",           tr: "Ne zaman kapanıyor?",         pron: "Ne sa-man ka-pa-nı-jor",      cat: "basics", sub: "Praktisch" },
  { id: 267, de: "Gibt es WiFi hier?",          tr: "Burada WiFi var mı?",         pron: "Bu-ra-da waj-faj war mı",     cat: "basics", sub: "Praktisch" },
  { id: 268, de: "Wo ist die Toilette?",        tr: "Tuvalet nerede?",             pron: "Tu-wa-let ne-re-de",           cat: "basics", sub: "Praktisch" },
  { id: 269, de: "Einen Moment bitte.",         tr: "Bir dakika lütfen.",          pron: "Bir da-ki-ka ljüt-fen",        cat: "basics", sub: "Praktisch" },
  { id: 270, de: "Sehr gerne! / Mit Freude!",  tr: "Memnuniyetle!",               pron: "Mem-nu-ni-jet-le",             cat: "basics", sub: "Praktisch" },
  { id: 271, de: "Schade! / Was ein Pech!",    tr: "Yazık! / Ne yazık ki!",       pron: "Ja-sık / Ne ja-sık ki",       cat: "basics", sub: "Praktisch" },
  { id: 272, de: "Gesundheit! (beim Niesen)",  tr: "Çok yaşa!",                   pron: "Tschok ja-scha",               cat: "basics", sub: "Praktisch" },
  { id: 273, de: "Glückwunsch!",               tr: "Tebrikler!",                  pron: "Teb-rik-ler",                  cat: "basics", sub: "Praktisch" },
  { id: 274, de: "Alles Gute!",                tr: "İyi şanslar! / Başarılar!",   pron: "İyi schan-slar / Ba-scha-rı-lar", cat: "basics", sub: "Praktisch" },
  { id: 275, de: "Zum Wohl! / Prost!",         tr: "Şerefe!",                     pron: "Sche-re-fe",                   cat: "basics", sub: "Praktisch" },

  // ─── FARBEN (fürs Einkaufen) ─────────────────────────────────────────────
  { id: 280, de: "rot",                         tr: "kırmızı",                     pron: "kır-mı-sı",                    cat: "urlaub", sub: "Farben" },
  { id: 281, de: "blau",                        tr: "mavi",                        pron: "ma-wi",                        cat: "urlaub", sub: "Farben" },
  { id: 282, de: "grün",                        tr: "yeşil",                       pron: "je-schil",                     cat: "urlaub", sub: "Farben" },
  { id: 283, de: "gelb",                        tr: "sarı",                        pron: "sa-rı",                        cat: "urlaub", sub: "Farben" },
  { id: 284, de: "weiß",                        tr: "beyaz",                       pron: "be-jas",                       cat: "urlaub", sub: "Farben" },
  { id: 285, de: "schwarz",                     tr: "siyah",                       pron: "si-jah",                       cat: "urlaub", sub: "Farben" },
  { id: 286, de: "braun",                       tr: "kahverengi",                  pron: "kah-we-ren-gi",                cat: "urlaub", sub: "Farben" },
  { id: 287, de: "orange",                      tr: "turuncu",                     pron: "tu-run-dschu",                 cat: "urlaub", sub: "Farben" },
  { id: 288, de: "rosa / pink",                 tr: "pembe",                       pron: "pem-be",                       cat: "urlaub", sub: "Farben" },
  { id: 289, de: "grau",                        tr: "gri",                         pron: "gri",                          cat: "urlaub", sub: "Farben" },
  { id: 290, de: "Haben Sie das in einer anderen Farbe?", tr: "Başka rengi var mı?", pron: "Basch-ka ren-gi war mı",   cat: "urlaub", sub: "Farben" },
  { id: 291, de: "Haben Sie das in einer anderen Größe?", tr: "Başka bedeni var mı?", pron: "Basch-ka be-de-ni war mı", cat: "urlaub", sub: "Farben" },
  { id: 292, de: "Das ist zu groß.",            tr: "Bu çok büyük.",               pron: "Bu tschok bjü-jük",            cat: "urlaub", sub: "Farben" },
  { id: 293, de: "Das ist zu klein.",           tr: "Bu çok küçük.",               pron: "Bu tschok kjü-tschük",         cat: "urlaub", sub: "Farben" },
  { id: 294, de: "Kann ich das anprobieren?",   tr: "Deneyebilir miyim?",          pron: "De-ne-je-bi-lir mi-jim",      cat: "urlaub", sub: "Farben" },

  // ─── ESSEN & GETRÄNKE ERWEITERT ──────────────────────────────────────────
  { id: 300, de: "Das Frühstück",               tr: "Kahvaltı",                    pron: "Kah-wal-tı",                   cat: "urlaub", sub: "Essen" },
  { id: 301, de: "Das Ei / Die Eier",           tr: "Yumurta",                     pron: "Ju-mur-ta",                    cat: "urlaub", sub: "Essen" },
  { id: 302, de: "Der Käse",                    tr: "Peynir",                      pron: "Pej-nir",                      cat: "urlaub", sub: "Essen" },
  { id: 303, de: "Der Joghurt",                 tr: "Yoğurt",                      pron: "Jo-urt",                       cat: "urlaub", sub: "Essen" },
  { id: 304, de: "Der Honig",                   tr: "Bal",                         pron: "bal",                          cat: "urlaub", sub: "Essen" },
  { id: 305, de: "Die Olive",                   tr: "Zeytin",                      pron: "Sej-tin",                      cat: "urlaub", sub: "Essen" },
  { id: 306, de: "Die Tomate",                  tr: "Domates",                     pron: "Do-ma-tes",                    cat: "urlaub", sub: "Essen" },
  { id: 307, de: "Die Gurke",                   tr: "Salatalık",                   pron: "Sa-la-ta-lık",                 cat: "urlaub", sub: "Essen" },
  { id: 308, de: "Die Suppe",                   tr: "Çorba",                       pron: "Tschor-ba",                    cat: "urlaub", sub: "Essen" },
  { id: 309, de: "Der Salat",                   tr: "Salata",                      pron: "Sa-la-ta",                     cat: "urlaub", sub: "Essen" },
  { id: 310, de: "Der Reis",                    tr: "Pilav",                       pron: "Pi-law",                       cat: "urlaub", sub: "Essen" },
  { id: 311, de: "Das Hähnchen",                tr: "Tavuk",                       pron: "Ta-wuk",                       cat: "urlaub", sub: "Essen" },
  { id: 312, de: "Das Lamm",                    tr: "Kuzu",                        pron: "Ku-su",                        cat: "urlaub", sub: "Essen" },
  { id: 313, de: "Die Garnelen",                tr: "Karides",                     pron: "Ka-ri-des",                    cat: "urlaub", sub: "Essen" },
  { id: 314, de: "Das Eis",                     tr: "Dondurma",                    pron: "Don-dur-ma",                   cat: "urlaub", sub: "Essen" },
  { id: 315, de: "Das Bier",                    tr: "Bira",                        pron: "Bi-ra",                        cat: "urlaub", sub: "Essen" },
  { id: 316, de: "Der Wein",                    tr: "Şarap",                       pron: "Scha-rap",                     cat: "urlaub", sub: "Essen" },
  { id: 317, de: "Der Fruchtsaft",              tr: "Meyve suyu",                  pron: "Mej-we su-ju",                 cat: "urlaub", sub: "Essen" },
  { id: 318, de: "Ayran (Joghurtgetränk)",      tr: "Ayran",                       pron: "Aj-ran",                       cat: "urlaub", sub: "Essen" },
  { id: 319, de: "Scharf / würzig",             tr: "Acı / Baharatlı",             pron: "A-dshı / Ba-ha-rat-lı",        cat: "urlaub", sub: "Essen" },
  { id: 320, de: "Nicht scharf bitte.",         tr: "Acısız lütfen.",              pron: "A-dshı-sıs ljüt-fen",          cat: "urlaub", sub: "Essen" },
  { id: 321, de: "Ohne ... bitte.",             tr: "... siz lütfen.",             pron: "sıs ljüt-fen",                 cat: "urlaub", sub: "Essen" },
  { id: 322, de: "Leitungswasser",              tr: "Musluk suyu",                 pron: "Mus-luk su-ju",                cat: "urlaub", sub: "Essen" },
  { id: 323, de: "Ein Glas / Eine Flasche",     tr: "Bir bardak / Bir şişe",       pron: "Bir bar-dak / Bir schi-sche",  cat: "urlaub", sub: "Essen" },

  // ─── WETTER ──────────────────────────────────────────────────────────────
  { id: 330, de: "Wie ist das Wetter?",         tr: "Hava nasıl?",                 pron: "Ha-wa na-sıl",                 cat: "basics", sub: "Wetter" },
  { id: 331, de: "Es ist kalt.",                tr: "Hava soğuk.",                 pron: "Ha-wa so-uk",                  cat: "basics", sub: "Wetter" },
  { id: 332, de: "Es ist warm.",                tr: "Hava sıcak.",                 pron: "Ha-wa sı-dschak",              cat: "basics", sub: "Wetter" },
  { id: 333, de: "Es regnet.",                  tr: "Yağmur yağıyor.",             pron: "Ja-mur ja-ı-jor",             cat: "basics", sub: "Wetter" },
  { id: 334, de: "Die Sonne scheint.",          tr: "Güneş parlıyor.",             pron: "Gjü-nesch par-lı-jor",         cat: "basics", sub: "Wetter" },
  { id: 335, de: "Es ist windig.",              tr: "Rüzgar var.",                 pron: "Rüs-gar war",                  cat: "basics", sub: "Wetter" },
  { id: 336, de: "Wird es morgen schön?",       tr: "Yarın hava güzel olacak mı?", pron: "Ja-rın ha-wa gjü-sel o-la-dshak mı", cat: "basics", sub: "Wetter" },
  { id: 337, de: "Das Gewitter",                tr: "Fırtına",                     pron: "Fır-tı-na",                    cat: "basics", sub: "Wetter" },
  { id: 338, de: "Der Schatten",                tr: "Gölge",                       pron: "Göl-ge",                       cat: "basics", sub: "Wetter" },

  // ─── VERBEN (Grundformen) ────────────────────────────────────────────────
  { id: 400, de: "sein",                        tr: "olmak",                       pron: "ol-mak",                        cat: "basics", sub: "Verben" },
  { id: 401, de: "haben",                       tr: "sahip olmak",                 pron: "sa-hip ol-mak",                 cat: "basics", sub: "Verben" },
  { id: 402, de: "machen / tun",                tr: "yapmak",                      pron: "jap-mak",                       cat: "basics", sub: "Verben" },
  { id: 403, de: "gehen",                       tr: "gitmek",                      pron: "git-mek",                       cat: "basics", sub: "Verben" },
  { id: 404, de: "kommen",                      tr: "gelmek",                      pron: "gel-mek",                       cat: "basics", sub: "Verben" },
  { id: 405, de: "wollen / möchten",            tr: "istemek",                     pron: "is-te-mek",                     cat: "basics", sub: "Verben" },
  { id: 406, de: "können",                      tr: "yapabilmek",                  pron: "ja-pa-bil-mek",                 cat: "basics", sub: "Verben" },
  { id: 407, de: "wissen",                      tr: "bilmek",                      pron: "bil-mek",                       cat: "basics", sub: "Verben" },
  { id: 408, de: "sehen",                       tr: "görmek",                      pron: "gör-mek",                       cat: "basics", sub: "Verben" },
  { id: 409, de: "geben",                       tr: "vermek",                      pron: "wer-mek",                       cat: "basics", sub: "Verben" },
  { id: 410, de: "nehmen",                      tr: "almak",                       pron: "al-mak",                        cat: "basics", sub: "Verben" },
  { id: 411, de: "sagen",                       tr: "söylemek",                    pron: "sjöj-le-mek",                   cat: "basics", sub: "Verben" },
  { id: 412, de: "finden",                      tr: "bulmak",                      pron: "bul-mak",                       cat: "basics", sub: "Verben" },
  { id: 413, de: "brauchen",                    tr: "ihtiyacı olmak",              pron: "ih-ti-ja-dschı ol-mak",         cat: "basics", sub: "Verben" },
  { id: 414, de: "kaufen",                      tr: "satın almak",                 pron: "sa-tın al-mak",                 cat: "basics", sub: "Verben" },
  { id: 415, de: "bezahlen",                    tr: "ödemek",                      pron: "ö-de-mek",                      cat: "basics", sub: "Verben" },
  { id: 416, de: "essen",                       tr: "yemek",                       pron: "je-mek",                        cat: "basics", sub: "Verben" },
  { id: 417, de: "trinken",                     tr: "içmek",                       pron: "itsch-mek",                     cat: "basics", sub: "Verben" },
  { id: 418, de: "schlafen",                    tr: "uyumak",                      pron: "u-ju-mak",                      cat: "basics", sub: "Verben" },
  { id: 419, de: "warten",                      tr: "beklemek",                    pron: "bek-le-mek",                    cat: "basics", sub: "Verben" },
  { id: 420, de: "helfen",                      tr: "yardım etmek",                pron: "jar-dım et-mek",                cat: "basics", sub: "Verben" },
  { id: 421, de: "verstehen",                   tr: "anlamak",                     pron: "an-la-mak",                     cat: "basics", sub: "Verben" },
  { id: 422, de: "sprechen",                    tr: "konuşmak",                    pron: "ko-nusch-mak",                  cat: "basics", sub: "Verben" },
  { id: 423, de: "fragen",                      tr: "sormak",                      pron: "sor-mak",                       cat: "basics", sub: "Verben" },
  { id: 424, de: "arbeiten",                    tr: "çalışmak",                    pron: "tscha-lısch-mak",               cat: "basics", sub: "Verben" },
  { id: 425, de: "fahren / gefahren werden",    tr: "sürmek",                      pron: "sjür-mek",                      cat: "basics", sub: "Verben" },
  { id: 426, de: "ankommen",                    tr: "varmak",                      pron: "war-mak",                       cat: "basics", sub: "Verben" },
  { id: 427, de: "beginnen / anfangen",         tr: "başlamak",                    pron: "basch-la-mak",                  cat: "basics", sub: "Verben" },
  { id: 428, de: "aufhören / beenden",          tr: "bitirmek",                    pron: "bi-tir-mek",                    cat: "basics", sub: "Verben" },
  { id: 429, de: "lieben / mögen",              tr: "sevmek",                      pron: "sew-mek",                       cat: "basics", sub: "Verben" },

  // ─── ADJEKTIVE ───────────────────────────────────────────────────────────
  { id: 440, de: "groß",                        tr: "büyük",                       pron: "bjü-jük",                       cat: "basics", sub: "Adjektive" },
  { id: 441, de: "klein",                       tr: "küçük",                       pron: "kjü-tschük",                    cat: "basics", sub: "Adjektive" },
  { id: 442, de: "gut",                         tr: "iyi",                         pron: "i-ji",                          cat: "basics", sub: "Adjektive" },
  { id: 443, de: "schlecht",                    tr: "kötü",                        pron: "kö-tü",                         cat: "basics", sub: "Adjektive" },
  { id: 444, de: "neu",                         tr: "yeni",                        pron: "je-ni",                         cat: "basics", sub: "Adjektive" },
  { id: 445, de: "alt",                         tr: "eski",                        pron: "es-ki",                         cat: "basics", sub: "Adjektive" },
  { id: 446, de: "schön",                       tr: "güzel",                       pron: "gjü-sel",                       cat: "basics", sub: "Adjektive" },
  { id: 447, de: "hässlich",                    tr: "çirkin",                      pron: "tschir-kin",                    cat: "basics", sub: "Adjektive" },
  { id: 448, de: "schnell",                     tr: "hızlı",                       pron: "hıs-lı",                        cat: "basics", sub: "Adjektive" },
  { id: 449, de: "langsam",                     tr: "yavaş",                       pron: "ja-wasch",                      cat: "basics", sub: "Adjektive" },
  { id: 450, de: "billig / günstig",            tr: "ucuz",                        pron: "u-dschus",                      cat: "basics", sub: "Adjektive" },
  { id: 451, de: "teuer",                       tr: "pahalı",                      pron: "pa-ha-lı",                      cat: "basics", sub: "Adjektive" },
  { id: 452, de: "sauber",                      tr: "temiz",                       pron: "te-mis",                        cat: "basics", sub: "Adjektive" },
  { id: 453, de: "schmutzig",                   tr: "kirli",                       pron: "kir-li",                        cat: "basics", sub: "Adjektive" },
  { id: 454, de: "leicht / einfach",            tr: "kolay",                       pron: "ko-laj",                        cat: "basics", sub: "Adjektive" },
  { id: 455, de: "schwierig",                   tr: "zor",                         pron: "sor",                           cat: "basics", sub: "Adjektive" },
  { id: 456, de: "voll",                        tr: "dolu",                        pron: "do-lu",                         cat: "basics", sub: "Adjektive" },
  { id: 457, de: "leer",                        tr: "boş",                         pron: "bosch",                         cat: "basics", sub: "Adjektive" },
  { id: 458, de: "nah",                         tr: "yakın",                       pron: "ja-kın",                        cat: "basics", sub: "Adjektive" },
  { id: 459, de: "weit / entfernt",             tr: "uzak",                        pron: "u-sak",                         cat: "basics", sub: "Adjektive" },
  { id: 460, de: "früh",                        tr: "erken",                       pron: "er-ken",                        cat: "basics", sub: "Adjektive" },
  { id: 461, de: "spät",                        tr: "geç",                         pron: "getsch",                        cat: "basics", sub: "Adjektive" },
  { id: 462, de: "müde",                        tr: "yorgun",                      pron: "jor-gun",                       cat: "basics", sub: "Adjektive" },
  { id: 463, de: "glücklich",                   tr: "mutlu",                       pron: "mut-lu",                        cat: "basics", sub: "Adjektive" },
  { id: 464, de: "traurig",                     tr: "üzgün",                       pron: "üs-gjün",                       cat: "basics", sub: "Adjektive" },
  { id: 465, de: "wichtig",                     tr: "önemli",                      pron: "ö-nem-li",                      cat: "basics", sub: "Adjektive" },

  // ─── FAMILIE ERWEITERT ───────────────────────────────────────────────────
  { id: 480, de: "Tante",                       tr: "Teyze / Hala",                pron: "Tej-se / Ha-la",                cat: "alltag", sub: "Familie" },
  { id: 481, de: "Onkel",                       tr: "Dayı / Amca",                 pron: "Da-jı / Am-dscha",              cat: "alltag", sub: "Familie" },
  { id: 482, de: "Cousin / Cousine",            tr: "Kuzen",                       pron: "Ku-sen",                        cat: "alltag", sub: "Familie" },
  { id: 483, de: "Schwiegermutter",             tr: "Kayınvalide",                 pron: "Ka-jın-wa-li-de",               cat: "alltag", sub: "Familie" },
  { id: 484, de: "Schwiegervater",              tr: "Kayınpeder",                  pron: "Ka-jın-pe-der",                 cat: "alltag", sub: "Familie" },
  { id: 485, de: "Schwager",                    tr: "Enişte / Kayınbirader",       pron: "E-nisch-te / Ka-jın-bi-ra-der", cat: "alltag", sub: "Familie" },
  { id: 486, de: "Schwägerin",                  tr: "Görümce / Yenge",             pron: "Gö-rüm-dsche / Jen-ge",         cat: "alltag", sub: "Familie" },
  { id: 487, de: "Enkelkind",                   tr: "Torun",                       pron: "To-run",                       cat: "alltag", sub: "Familie" },
  { id: 488, de: "Baby",                        tr: "Bebek",                       pron: "Be-bek",                        cat: "alltag", sub: "Familie" },
  { id: 489, de: "Verlobte/r",                  tr: "Nişanlı",                     pron: "Ni-schan-lı",                   cat: "alltag", sub: "Familie" },
  { id: 490, de: "Freund/in (Beziehung)",       tr: "Sevgili",                     pron: "Sew-gi-li",                     cat: "alltag", sub: "Familie" },
  { id: 491, de: "Freund/in (platonisch)",      tr: "Arkadaş",                     pron: "Ar-ka-dasch",                   cat: "alltag", sub: "Familie" },

  // ─── WEGBESCHREIBUNG ─────────────────────────────────────────────────────
  { id: 500, de: "Wie komme ich zu ...?",       tr: "... nasıl gidebilirim?",      pron: "... na-sıl gi-de-bi-li-rim",   cat: "urlaub", sub: "Wegbeschreibung" },
  { id: 501, de: "Ist das in der Nähe?",        tr: "Bu yakında mı?",              pron: "Bu ja-kın-da mı",               cat: "urlaub", sub: "Wegbeschreibung" },
  { id: 502, de: "Zu Fuß oder mit dem Auto?",   tr: "Yürüyerek mi, arabayla mı?",  pron: "Jü-rü-je-rek mi, a-ra-baj-la mı", cat: "urlaub", sub: "Wegbeschreibung" },
  { id: 503, de: "An der Ampel links.",         tr: "Trafik ışığında sola.",       pron: "Tra-fik ı-schı-ın-da so-la",   cat: "urlaub", sub: "Wegbeschreibung" },
  { id: 504, de: "An der Ecke rechts.",         tr: "Köşeden sağa.",               pron: "Kö-sche-den saa",              cat: "urlaub", sub: "Wegbeschreibung" },
  { id: 505, de: "Gegenüber von ...",           tr: "... karşısında",              pron: "kar-schı-sın-da",              cat: "urlaub", sub: "Wegbeschreibung" },
  { id: 506, de: "Neben ...",                   tr: "... yanında",                 pron: "ja-nın-da",                    cat: "urlaub", sub: "Wegbeschreibung" },
  { id: 507, de: "Zwischen ... und ...",        tr: "... ile ... arasında",        pron: "i-le ... a-ra-sın-da",         cat: "urlaub", sub: "Wegbeschreibung" },
  { id: 508, de: "Die erste Straße rechts.",    tr: "İlk sokak sağda.",            pron: "İlk so-kak saa-da",            cat: "urlaub", sub: "Wegbeschreibung" },
  { id: 509, de: "Ich habe mich verlaufen.",    tr: "Kayboldum.",                  pron: "Kaj-bol-dum",                  cat: "urlaub", sub: "Wegbeschreibung" },
  { id: 510, de: "Können Sie mir helfen?",      tr: "Bana yardım edebilir misiniz?", pron: "Ba-na jar-dım e-de-bi-lir mi-si-nis", cat: "urlaub", sub: "Wegbeschreibung" },
  { id: 511, de: "Die Karte / Der Stadtplan",   tr: "Harita",                      pron: "Ha-ri-ta",                     cat: "urlaub", sub: "Wegbeschreibung" },

  // ─── VERKEHRSMITTEL ──────────────────────────────────────────────────────
  { id: 520, de: "Der Bus",                     tr: "Otobüs",                      pron: "O-to-bjüs",                    cat: "urlaub", sub: "Verkehrsmittel" },
  { id: 521, de: "Die Fähre",                   tr: "Vapur / Feribot",             pron: "Wa-pur / Fe-ri-bot",           cat: "urlaub", sub: "Verkehrsmittel" },
  { id: 522, de: "Die U-Bahn",                  tr: "Metro",                       pron: "Met-ro",                       cat: "urlaub", sub: "Verkehrsmittel" },
  { id: 523, de: "Die Straßenbahn",             tr: "Tramvay",                     pron: "Tram-waj",                     cat: "urlaub", sub: "Verkehrsmittel" },
  { id: 524, de: "Der Minibus (Sammeltaxi)",    tr: "Dolmuş",                      pron: "Dol-musch",                    cat: "urlaub", sub: "Verkehrsmittel" },
  { id: 525, de: "Der Mietwagen",               tr: "Kiralık araba",               pron: "Ki-ra-lık a-ra-ba",            cat: "urlaub", sub: "Verkehrsmittel" },
  { id: 526, de: "Die Bushaltestelle",          tr: "Otobüs durağı",               pron: "O-to-bjüs du-raa",             cat: "urlaub", sub: "Verkehrsmittel" },
  { id: 527, de: "Einfache Fahrt",              tr: "Tek yön",                     pron: "Tek jön",                      cat: "urlaub", sub: "Verkehrsmittel" },
  { id: 528, de: "Hin- und Rückfahrt",          tr: "Gidiş dönüş",                 pron: "Gi-dish dö-njüsch",            cat: "urlaub", sub: "Verkehrsmittel" },
  { id: 529, de: "Wo muss ich umsteigen?",      tr: "Nerede aktarma yapmalıyım?",  pron: "Ne-re-de ak-tar-ma jap-ma-lı-jım", cat: "urlaub", sub: "Verkehrsmittel" },
  { id: 530, de: "Ist dieser Platz frei?",      tr: "Bu koltuk boş mu?",           pron: "Bu kol-tuk bosch mu",          cat: "urlaub", sub: "Verkehrsmittel" },
  { id: 531, de: "Der Koffer / Das Gepäck",     tr: "Bavul / Bagaj",               pron: "Ba-wul / Ba-gash",             cat: "urlaub", sub: "Verkehrsmittel" },

  // ─── ZEIT DETAIL ─────────────────────────────────────────────────────────
  { id: 540, de: "Um wie viel Uhr?",            tr: "Saat kaçta?",                 pron: "Sa-at katsch-ta",              cat: "basics", sub: "Zeit" },
  { id: 541, de: "Es ist drei Uhr.",            tr: "Saat üç.",                    pron: "Sa-at ütsch",                  cat: "basics", sub: "Zeit" },
  { id: 542, de: "Halb vier.",                  tr: "Üç buçuk.",                   pron: "Ütsch bu-tschuk",              cat: "basics", sub: "Zeit" },
  { id: 543, de: "Viertel nach zwei.",          tr: "İkiyi çeyrek geçiyor.",       pron: "İ-ki-ji tschej-rek ge-tschi-jor", cat: "basics", sub: "Zeit" },
  { id: 544, de: "diese Woche",                 tr: "bu hafta",                    pron: "bu haf-ta",                    cat: "basics", sub: "Zeit" },
  { id: 545, de: "nächste Woche",               tr: "gelecek hafta",               pron: "ge-le-dschek haf-ta",          cat: "basics", sub: "Zeit" },
  { id: 546, de: "letzte Woche",                tr: "geçen hafta",                 pron: "ge-tschen haf-ta",             cat: "basics", sub: "Zeit" },
  { id: 547, de: "dieser Monat",                tr: "bu ay",                       pron: "bu aj",                        cat: "basics", sub: "Zeit" },
  { id: 548, de: "morgens",                     tr: "sabahleyin",                  pron: "sa-bah-le-jin",                cat: "basics", sub: "Zeit" },
  { id: 549, de: "abends",                      tr: "akşamları",                   pron: "ak-scham-la-rı",               cat: "basics", sub: "Zeit" },
  { id: 550, de: "immer",                       tr: "her zaman",                   pron: "her sa-man",                   cat: "basics", sub: "Zeit" },
  { id: 551, de: "nie",                         tr: "asla / hiçbir zaman",         pron: "as-la / hitsch-bir sa-man",    cat: "basics", sub: "Zeit" },
  { id: 552, de: "manchmal",                    tr: "bazen",                       pron: "ba-sen",                       cat: "basics", sub: "Zeit" },
  { id: 553, de: "jetzt",                       tr: "şimdi",                       pron: "schim-di",                     cat: "basics", sub: "Zeit" },
  { id: 554, de: "später",                      tr: "sonra",                       pron: "son-ra",                       cat: "basics", sub: "Zeit" },

  // ─── UNTERKUNFT & CAMPING ────────────────────────────────────────────────
  { id: 560, de: "Die Klimaanlage",             tr: "Klima",                       pron: "Kli-ma",                       cat: "urlaub", sub: "Unterkunft" },
  { id: 561, de: "Die Heizung",                 tr: "Kalorifer",                   pron: "Ka-lo-ri-fer",                 cat: "urlaub", sub: "Unterkunft" },
  { id: 562, de: "Der Balkon",                  tr: "Balkon",                      pron: "Bal-kon",                      cat: "urlaub", sub: "Unterkunft" },
  { id: 563, de: "Die Aussicht / Der Meerblick",tr: "Manzara / Deniz manzarası",   pron: "Man-sa-ra / De-nis man-sa-ra-sı", cat: "urlaub", sub: "Unterkunft" },
  { id: 564, de: "Funktioniert nicht.",         tr: "Çalışmıyor.",                 pron: "Tscha-lısch-mı-jor",           cat: "urlaub", sub: "Unterkunft" },
  { id: 565, de: "Es gibt kein warmes Wasser.", tr: "Sıcak su yok.",               pron: "Sı-dschak su jok",             cat: "urlaub", sub: "Unterkunft" },
  { id: 566, de: "Können Sie mich um 7 Uhr wecken?", tr: "Beni yedide uyandırabilir misiniz?", pron: "Be-ni je-di-de u-jan-dı-ra-bi-lir mi-si-nis", cat: "urlaub", sub: "Unterkunft" },
  { id: 567, de: "Das Zimmer ist zu laut.",     tr: "Oda çok gürültülü.",          pron: "O-da tschok gjü-rül-tü-lü",    cat: "urlaub", sub: "Unterkunft" },
  { id: 568, de: "Können wir das Zimmer wechseln?", tr: "Odayı değiştirebilir miyiz?", pron: "O-da-jı de-isch-ti-re-bi-lir mi-jis", cat: "urlaub", sub: "Unterkunft" },
  { id: 569, de: "Wo kann ich Wäsche waschen?", tr: "Nerede çamaşır yıkayabilirim?", pron: "Ne-re-de tscha-ma-schır jı-ka-ja-bi-li-rim", cat: "urlaub", sub: "Unterkunft" },
  { id: 570, de: "Der Safe / Tresor",           tr: "Kasa",                        pron: "Ka-sa",                        cat: "urlaub", sub: "Unterkunft" },
  { id: 571, de: "Die Bettwäsche",              tr: "Nevresim",                    pron: "Ne-wre-sim",                   cat: "urlaub", sub: "Unterkunft" },
];

const CATEGORIES = [
  { id: "all",     label: "Alle",          icon: "📚" },
  { id: "basics",  label: "Basics",        icon: "💬" },
  { id: "urlaub",  label: "Urlaub",        icon: "🏖️" },
  { id: "alltag",  label: "Alltag",        icon: "🏠" },
];

const SUBCATEGORIES = [...new Set(VOCABULARY.map(v => v.sub))];
